/* automatically generated by rust-bindgen 0.69.5 */

pub const _ALCP_ALCP_H_: u32 = 2;
pub const _ALCP_MACROS_H_: u32 = 2;
pub const _ALCP_TYPES_H_: u32 = 2;
pub const _ALCP_ERROR_H_: u32 = 2;
pub const _ALCP_KEY_H_: u32 = 2;
pub const _ALCP_CIPHER_H_: u32 = 2;
pub const _ALCP_CIPHER_AEAD_H_: u32 = 2;
pub const _ALCP_CIPHER_SEGMENT_H_: u32 = 2;
pub const _ALCP_DIGEST_H: u32 = 2;
pub const _ALCP_MAC_H_: u32 = 2;
pub const _ALCP_RNG_H_: u32 = 2;
pub const _ALCP_DRBG_H_: u32 = 2;
pub const _ALCP_ECDH_H_: u32 = 2;
pub const _ALCP_EC_H_: u32 = 2;
pub const _VERSION_H_: u32 = 2;
pub const _ALCP_RSA_H_: u32 = 2;
pub const bool__false_: bool_ = 0;
pub const bool__true_: bool_ = 1;
pub type bool_ = ::std::os::raw::c_int;
pub type Int8 = i8;
pub type Int16 = i16;
pub type Int32 = i32;
pub type Int64 = i64;
pub type Uint8 = u8;
pub type Uint16 = u16;
pub type Uint32 = u32;
pub type Uint64 = u64;
pub type VoidP = *mut ::std::os::raw::c_void;
pub type Int8P = *mut i8;
pub type Int16P = *mut i16;
pub type Int32P = *mut i32;
pub type Int64P = *mut i64;
pub type Uint8P = *mut u8;
pub type Uint16P = *mut u16;
pub type Uint32P = *mut u32;
pub type Uint64P = *mut u64;
pub type AlcHandleP = VoidP;
pub const _alc_error_generic_ALC_ERROR_NONE: _alc_error_generic = 0;
pub const _alc_error_generic_ALC_ERROR_GENERIC: _alc_error_generic = 1;
pub const _alc_error_generic_ALC_ERROR_NOT_SUPPORTED: _alc_error_generic = 2;
pub const _alc_error_generic_ALC_ERROR_NOT_PERMITTED: _alc_error_generic = 3;
pub const _alc_error_generic_ALC_ERROR_EXISTS: _alc_error_generic = 4;
pub const _alc_error_generic_ALC_ERROR_NOT_EXISTS: _alc_error_generic = 5;
pub const _alc_error_generic_ALC_ERROR_INVALID_ARG: _alc_error_generic = 6;
pub const _alc_error_generic_ALC_ERROR_BAD_STATE: _alc_error_generic = 7;
pub const _alc_error_generic_ALC_ERROR_NO_MEMORY: _alc_error_generic = 8;
pub const _alc_error_generic_ALC_ERROR_INVALID_DATA: _alc_error_generic = 9;
pub const _alc_error_generic_ALC_ERROR_INVALID_SIZE: _alc_error_generic = 10;
pub const _alc_error_generic_ALC_ERROR_HARDWARE_FAILURE: _alc_error_generic = 11;
pub const _alc_error_generic_ALC_ERROR_NO_ENTROPY: _alc_error_generic = 12;
pub const _alc_error_generic_ALC_ERROR_DUPLICATE_KEY: _alc_error_generic = 13;
pub const _alc_error_generic_ALC_ERROR_TAG_MISMATCH: _alc_error_generic = 14;
pub type _alc_error_generic = ::std::os::raw::c_int;
pub use self::_alc_error_generic as alc_error_generic_t;
pub type alc_error_t = Uint64;
extern "C" {
    pub fn alcp_is_error(err: alc_error_t) -> Uint8;
}
pub const alc_key_len_ALC_KEY_LEN_128: alc_key_len = 128;
pub const alc_key_len_ALC_KEY_LEN_192: alc_key_len = 192;
pub const alc_key_len_ALC_KEY_LEN_256: alc_key_len = 256;
pub const alc_key_len_ALC_KEY_LEN_384: alc_key_len = 384;
pub const alc_key_len_ALC_KEY_LEN_512: alc_key_len = 512;
pub const alc_key_len_ALC_KEY_LEN_1024: alc_key_len = 1024;
pub const alc_key_len_ALC_KEY_LEN_2048: alc_key_len = 2048;
pub const alc_key_len_ALC_KEY_LEN_4096: alc_key_len = 4096;
pub const alc_key_len_ALC_KEY_LEN_CUSTOM: alc_key_len = 4097;
pub const alc_key_len_ALC_KEY_LEN_DEFAULT: alc_key_len = 128;
pub type alc_key_len = ::std::os::raw::c_int;
pub use self::alc_key_len as alc_key_len_t;
pub const _alc_cipher_mode_ALC_AES_MODE_NONE: _alc_cipher_mode = 0;
pub const _alc_cipher_mode_ALC_AES_MODE_ECB: _alc_cipher_mode = 1;
pub const _alc_cipher_mode_ALC_AES_MODE_CBC: _alc_cipher_mode = 2;
pub const _alc_cipher_mode_ALC_AES_MODE_OFB: _alc_cipher_mode = 3;
pub const _alc_cipher_mode_ALC_AES_MODE_CTR: _alc_cipher_mode = 4;
pub const _alc_cipher_mode_ALC_AES_MODE_CFB: _alc_cipher_mode = 5;
pub const _alc_cipher_mode_ALC_AES_MODE_XTS: _alc_cipher_mode = 6;
pub const _alc_cipher_mode_ALC_CHACHA20: _alc_cipher_mode = 7;
pub const _alc_cipher_mode_ALC_AES_MODE_GCM: _alc_cipher_mode = 8;
pub const _alc_cipher_mode_ALC_AES_MODE_CCM: _alc_cipher_mode = 9;
pub const _alc_cipher_mode_ALC_AES_MODE_SIV: _alc_cipher_mode = 10;
pub const _alc_cipher_mode_ALC_CHACHA20_POLY1305: _alc_cipher_mode = 11;
pub const _alc_cipher_mode_ALC_AES_MODE_MAX: _alc_cipher_mode = 12;
pub type _alc_cipher_mode = ::std::os::raw::c_int;
pub use self::_alc_cipher_mode as alc_cipher_mode_t;
#[repr(C)]
#[repr(align(64))]
#[derive(Debug, Copy, Clone)]
pub struct _alc_cipher_state {
    pub alcp_exp_enc_key: [Uint64; 64usize],
    pub alcp_exp_dec_key: [Uint64; 64usize],
    pub alcp_precomputed_table: [Uint64; 64usize],
    pub alcp_keyLen_in_bytes: Uint32,
}
impl Default for _alc_cipher_state {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type alc_cipher_state_t = _alc_cipher_state;
pub type alc_cipher_context_t = ::std::os::raw::c_void;
pub type alc_cipher_context_p = *mut alc_cipher_context_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _alc_cipher_handle {
    pub ch_context: alc_cipher_context_p,
}
impl Default for _alc_cipher_handle {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type alc_cipher_handle_t = _alc_cipher_handle;
pub type alc_cipher_handle_p = *mut _alc_cipher_handle;
extern "C" {
    pub fn alcp_cipher_context_size() -> Uint64;
}
extern "C" {
    pub fn alcp_cipher_request(
        cipherMode: alc_cipher_mode_t,
        keyLen: Uint64,
        pCipherHandle: alc_cipher_handle_p,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_cipher_init(
        pCipherHandle: alc_cipher_handle_p,
        pKey: *const Uint8,
        keyLen: Uint64,
        pIv: *const Uint8,
        ivLen: Uint64,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_cipher_encrypt(
        pCipherHandle: alc_cipher_handle_p,
        pPlainText: *const Uint8,
        pCipherText: *mut Uint8,
        datalen: Uint64,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_cipher_decrypt(
        pCipherHandle: alc_cipher_handle_p,
        pCipherText: *const Uint8,
        pPlainText: *mut Uint8,
        datalen: Uint64,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_cipher_finish(pCipherHandle: alc_cipher_handle_p);
}
extern "C" {
    pub fn alcp_cipher_aead_context_size() -> Uint64;
}
extern "C" {
    pub fn alcp_cipher_aead_request(
        cipherMode: alc_cipher_mode_t,
        keyLen: Uint64,
        pCipherHandle: alc_cipher_handle_p,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_cipher_aead_request_with_extState(
        mode: alc_cipher_mode_t,
        keyLen: Uint64,
        pCipherState: *mut alc_cipher_state_t,
        pCipherHandle: alc_cipher_handle_p,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_cipher_aead_init(
        pCipherHandle: alc_cipher_handle_p,
        pKey: *const Uint8,
        keyLen: Uint64,
        pIv: *const Uint8,
        ivLen: Uint64,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_cipher_aead_encrypt(
        pCipherHandle: alc_cipher_handle_p,
        pInput: *const Uint8,
        pOutput: *mut Uint8,
        len: Uint64,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_cipher_aead_decrypt(
        pCipherHandle: alc_cipher_handle_p,
        pInput: *const Uint8,
        pOutput: *mut Uint8,
        len: Uint64,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_cipher_aead_set_aad(
        pCipherHandle: alc_cipher_handle_p,
        pInput: *const Uint8,
        len: Uint64,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_cipher_aead_get_tag(
        pCipherHandle: alc_cipher_handle_p,
        pOutput: *mut Uint8,
        tagLen: Uint64,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_cipher_aead_set_tag_length(
        pCipherHandle: alc_cipher_handle_p,
        tagLen: Uint64,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_cipher_aead_set_ccm_plaintext_length(
        pCipherHandle: alc_cipher_handle_p,
        plaintextLength: Uint64,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_cipher_aead_finish(pCipherHandle: alc_cipher_handle_p);
}
extern "C" {
    pub fn alcp_cipher_segment_init(
        pCipherHandle: alc_cipher_handle_p,
        pKey: *const Uint8,
        keyLen: Uint64,
        pIv: *const Uint8,
        ivLen: Uint64,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_cipher_segment_request(
        cipherMode: alc_cipher_mode_t,
        keyLen: Uint64,
        pCipherHandle: alc_cipher_handle_p,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_cipher_segment_encrypt_xts(
        pCipherHandle: alc_cipher_handle_p,
        pPlainText: *const Uint8,
        pCipherText: *mut Uint8,
        currPlainTextLen: Uint64,
        startBlockNum: Uint64,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_cipher_segment_decrypt_xts(
        pCipherHandle: alc_cipher_handle_p,
        pCipherText: *const Uint8,
        pPlainText: *mut Uint8,
        currCipherTextLen: Uint64,
        startBlockNum: Uint64,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_cipher_segment_finish(pCipherHandle: alc_cipher_handle_p);
}
pub const _alc_digest_len_ALC_DIGEST_LEN_128: _alc_digest_len = 128;
pub const _alc_digest_len_ALC_DIGEST_LEN_192: _alc_digest_len = 192;
pub const _alc_digest_len_ALC_DIGEST_LEN_160: _alc_digest_len = 160;
pub const _alc_digest_len_ALC_DIGEST_LEN_288: _alc_digest_len = 288;
pub const _alc_digest_len_ALC_DIGEST_LEN_224: _alc_digest_len = 224;
pub const _alc_digest_len_ALC_DIGEST_LEN_256: _alc_digest_len = 256;
pub const _alc_digest_len_ALC_DIGEST_LEN_384: _alc_digest_len = 384;
pub const _alc_digest_len_ALC_DIGEST_LEN_512: _alc_digest_len = 512;
pub const _alc_digest_len_ALC_DIGEST_LEN_CUSTOM_SHAKE_128: _alc_digest_len = 17;
pub const _alc_digest_len_ALC_DIGEST_LEN_CUSTOM_SHAKE_256: _alc_digest_len = 18;
pub type _alc_digest_len = ::std::os::raw::c_int;
pub use self::_alc_digest_len as alc_digest_len_t;
pub const alc_digest_block_size_ALC_DIGEST_BLOCK_SIZE_MD5: alc_digest_block_size = 512;
pub const alc_digest_block_size_ALC_DIGEST_BLOCK_SIZE_SHA1: alc_digest_block_size = 512;
pub const alc_digest_block_size_ALC_DIGEST_BLOCK_SIZE_MD5_SHA1: alc_digest_block_size = 512;
pub const alc_digest_block_size_ALC_DIGEST_BLOCK_SIZE_SHA2_256: alc_digest_block_size = 512;
pub const alc_digest_block_size_ALC_DIGEST_BLOCK_SIZE_SHA2_512: alc_digest_block_size = 1024;
pub const alc_digest_block_size_ALC_DIGEST_BLOCK_SIZE_SHA3_224: alc_digest_block_size = 1152;
pub const alc_digest_block_size_ALC_DIGEST_BLOCK_SIZE_SHA3_256: alc_digest_block_size = 1088;
pub const alc_digest_block_size_ALC_DIGEST_BLOCK_SIZE_SHA3_384: alc_digest_block_size = 832;
pub const alc_digest_block_size_ALC_DIGEST_BLOCK_SIZE_SHA3_512: alc_digest_block_size = 576;
pub const alc_digest_block_size_ALC_DIGEST_BLOCK_SIZE_SHAKE_128: alc_digest_block_size = 1344;
pub const alc_digest_block_size_ALC_DIGEST_BLOCK_SIZE_SHAKE_256: alc_digest_block_size = 1088;
pub type alc_digest_block_size = ::std::os::raw::c_int;
pub use self::alc_digest_block_size as alc_digest_block_size_t;
pub const _alc_digest_mode_ALC_MD5: _alc_digest_mode = 0;
pub const _alc_digest_mode_ALC_SHA1: _alc_digest_mode = 1;
pub const _alc_digest_mode_ALC_MD5_SHA1: _alc_digest_mode = 2;
pub const _alc_digest_mode_ALC_SHA2_224: _alc_digest_mode = 3;
pub const _alc_digest_mode_ALC_SHA2_256: _alc_digest_mode = 4;
pub const _alc_digest_mode_ALC_SHA2_384: _alc_digest_mode = 5;
pub const _alc_digest_mode_ALC_SHA2_512: _alc_digest_mode = 6;
pub const _alc_digest_mode_ALC_SHA2_512_224: _alc_digest_mode = 7;
pub const _alc_digest_mode_ALC_SHA2_512_256: _alc_digest_mode = 8;
pub const _alc_digest_mode_ALC_SHA3_224: _alc_digest_mode = 9;
pub const _alc_digest_mode_ALC_SHA3_256: _alc_digest_mode = 10;
pub const _alc_digest_mode_ALC_SHA3_384: _alc_digest_mode = 11;
pub const _alc_digest_mode_ALC_SHA3_512: _alc_digest_mode = 12;
pub const _alc_digest_mode_ALC_SHAKE_128: _alc_digest_mode = 13;
pub const _alc_digest_mode_ALC_SHAKE_256: _alc_digest_mode = 14;
pub type _alc_digest_mode = ::std::os::raw::c_int;
pub use self::_alc_digest_mode as alc_digest_mode_t;
pub type alc_diget_mode_p = *mut _alc_digest_mode;
pub type alc_digest_context_t = ::std::os::raw::c_void;
pub type alc_digest_context_p = *mut alc_digest_context_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _alc_digest_handle {
    pub context: alc_digest_context_p,
}
impl Default for _alc_digest_handle {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type alc_digest_handle_t = _alc_digest_handle;
pub type alc_digest_handle_p = *mut _alc_digest_handle;
pub type AlcDigestHandle = _alc_digest_handle;
pub type AlcDigestHandleP = *mut _alc_digest_handle;
extern "C" {
    pub fn alcp_digest_context_size() -> Uint64;
}
extern "C" {
    pub fn alcp_digest_request(
        mode: alc_digest_mode_t,
        p_digest_handle: alc_digest_handle_p,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_digest_init(p_digest_handle: alc_digest_handle_p) -> alc_error_t;
}
extern "C" {
    pub fn alcp_digest_update(
        p_digest_handle: alc_digest_handle_p,
        buf: *const Uint8,
        size: Uint64,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_digest_finalize(
        p_digest_handle: alc_digest_handle_p,
        buf: *mut Uint8,
        size: Uint64,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_digest_finish(p_digest_handle: alc_digest_handle_p);
}
extern "C" {
    pub fn alcp_digest_context_copy(
        pSrcHandle: alc_digest_handle_p,
        pDestHandle: alc_digest_handle_p,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_digest_shake_squeeze(
        pDigestHandle: alc_digest_handle_p,
        pBuff: *mut Uint8,
        size: Uint64,
    ) -> alc_error_t;
}
pub const _alc_mac_type_ALC_MAC_HMAC: _alc_mac_type = 0;
pub const _alc_mac_type_ALC_MAC_CMAC: _alc_mac_type = 1;
pub const _alc_mac_type_ALC_MAC_POLY1305: _alc_mac_type = 2;
pub type _alc_mac_type = ::std::os::raw::c_int;
pub use self::_alc_mac_type as alc_mac_type_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _alc_hmac_info {
    pub digest_mode: alc_digest_mode_t,
}
impl Default for _alc_hmac_info {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type alc_hmac_info_t = _alc_hmac_info;
pub type alc_hmac_info_p = *mut _alc_hmac_info;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _alc_cmac_info {
    pub ci_mode: alc_cipher_mode_t,
}
impl Default for _alc_cmac_info {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type alc_cmac_info_t = _alc_cmac_info;
pub type alc_cmac_info_p = *mut _alc_cmac_info;
#[repr(C)]
#[derive(Copy, Clone)]
pub union _mac_info {
    pub hmac: alc_hmac_info_t,
    pub cmac: alc_cmac_info_t,
}
impl Default for _mac_info {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type alc_mac_info_t = _mac_info;
pub type alc_mac_context_t = ::std::os::raw::c_void;
pub type alc_mac_context_p = *mut alc_mac_context_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct alc_mac_handle {
    pub ch_context: alc_mac_context_p,
}
impl Default for alc_mac_handle {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type alc_mac_handle_t = alc_mac_handle;
pub type alc_mac_handle_p = *mut alc_mac_handle;
pub type AlcMacHandle = alc_mac_handle;
extern "C" {
    pub fn alcp_mac_context_size() -> Uint64;
}
extern "C" {
    pub fn alcp_mac_request(pMacHandle: alc_mac_handle_p, macType: alc_mac_type_t) -> alc_error_t;
}
extern "C" {
    pub fn alcp_mac_init(
        pMacHandle: alc_mac_handle_p,
        key: *const Uint8,
        size: Uint64,
        info: *mut alc_mac_info_t,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_mac_update(
        pMacHandle: alc_mac_handle_p,
        buff: *const Uint8,
        size: Uint64,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_mac_finalize(
        pMacHandle: alc_mac_handle_p,
        buff: *mut Uint8,
        size: Uint64,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_mac_finish(pMacHandle: alc_mac_handle_p) -> alc_error_t;
}
extern "C" {
    pub fn alcp_mac_reset(pMacHandle: alc_mac_handle_p) -> alc_error_t;
}
extern "C" {
    pub fn alcp_mac_context_copy(
        pSrcHandle: alc_mac_handle_p,
        pDestHandle: alc_mac_handle_p,
    ) -> alc_error_t;
}
pub const alc_rng_type_t_ALC_RNG_TYPE_INVALID: alc_rng_type_t = 0;
pub const alc_rng_type_t_ALC_RNG_TYPE_SIMPLE: alc_rng_type_t = 1;
pub const alc_rng_type_t_ALC_RNG_TYPE_CONTINUOUS: alc_rng_type_t = 2;
pub const alc_rng_type_t_ALC_RNG_TYPE_DISCRETE: alc_rng_type_t = 3;
pub const alc_rng_type_t_ALC_RNG_TYPE_MAX: alc_rng_type_t = 4;
pub type alc_rng_type_t = ::std::os::raw::c_int;
pub const alc_rng_source_t_ALC_RNG_SOURCE_ALGO: alc_rng_source_t = 0;
pub const alc_rng_source_t_ALC_RNG_SOURCE_OS: alc_rng_source_t = 1;
pub const alc_rng_source_t_ALC_RNG_SOURCE_DEV: alc_rng_source_t = 2;
pub const alc_rng_source_t_ALC_RNG_SOURCE_ARCH: alc_rng_source_t = 3;
pub const alc_rng_source_t_ALC_RNG_SOURCE_MAX: alc_rng_source_t = 4;
pub type alc_rng_source_t = ::std::os::raw::c_int;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_UNKNOWN: alc_rng_distrib_t = 0;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_BETA: alc_rng_distrib_t = 1;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_CAUCHY: alc_rng_distrib_t = 2;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_CHISQUARE: alc_rng_distrib_t = 3;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_DIRICHLET: alc_rng_distrib_t = 4;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_EXPONENTIAL: alc_rng_distrib_t = 5;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_GAMMA: alc_rng_distrib_t = 6;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_GAUSSIAN: alc_rng_distrib_t = 7;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_GUMBEL: alc_rng_distrib_t = 8;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_LAPLACE: alc_rng_distrib_t = 9;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_LOGISTIC: alc_rng_distrib_t = 10;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_LOGNORMAL: alc_rng_distrib_t = 11;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_PARETO: alc_rng_distrib_t = 12;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_RAYLEIGH: alc_rng_distrib_t = 13;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_UNIFORM: alc_rng_distrib_t = 14;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_VONMISES: alc_rng_distrib_t = 15;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_WEIBULL: alc_rng_distrib_t = 16;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_WALD: alc_rng_distrib_t = 17;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_ZIPF: alc_rng_distrib_t = 18;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_BERNOULLI: alc_rng_distrib_t = 19;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_BINOMIAL: alc_rng_distrib_t = 20;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_GEOMETRIC: alc_rng_distrib_t = 21;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_HYPERGEOMETRIC: alc_rng_distrib_t = 22;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_MULTINOMIAL: alc_rng_distrib_t = 23;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_NEGBINOMIAL: alc_rng_distrib_t = 24;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_POISSON: alc_rng_distrib_t = 25;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_UNIFORM_BITS: alc_rng_distrib_t = 26;
pub const alc_rng_distrib_t_ALC_RNG_DISTRIB_MAX: alc_rng_distrib_t = 27;
pub type alc_rng_distrib_t = ::std::os::raw::c_int;
pub const _alc_rng_algo_flags_ALC_RNG_FLAG_DUMMY: _alc_rng_algo_flags = 0;
pub type _alc_rng_algo_flags = ::std::os::raw::c_int;
pub use self::_alc_rng_algo_flags as alc_rng_algo_flags_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _alc_rng_info {
    pub ri_type: alc_rng_type_t,
    pub ri_source: alc_rng_source_t,
    pub ri_distrib: alc_rng_distrib_t,
    pub ri_flags: alc_rng_algo_flags_t,
}
impl Default for _alc_rng_info {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type alc_rng_info_t = _alc_rng_info;
pub type alc_rng_info_p = *mut _alc_rng_info;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct alc_rng_handle_t {
    pub rh_context: *mut ::std::os::raw::c_void,
}
impl Default for alc_rng_handle_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type alc_rng_handle_p = *mut alc_rng_handle_t;
pub type AlcRngHandle = alc_rng_handle_t;
pub type AlcRngHandleP = *mut alc_rng_handle_t;
extern "C" {
    pub fn alcp_rng_supported(pRngInfo: alc_rng_info_p) -> alc_error_t;
}
extern "C" {
    pub fn alcp_rng_context_size(pRngInfo: alc_rng_info_p) -> Uint64;
}
extern "C" {
    pub fn alcp_rng_request(pRngInfo: alc_rng_info_p, pRngHandle: alc_rng_handle_p) -> alc_error_t;
}
extern "C" {
    pub fn alcp_rng_gen_random(
        pRngHandle: alc_rng_handle_p,
        pBuf: *mut Uint8,
        size: Uint64,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_rng_init(pRngHandle: alc_rng_handle_p) -> alc_error_t;
}
extern "C" {
    pub fn alcp_rng_seed(
        pRngHandle: alc_rng_handle_p,
        seed: *const Uint8,
        size: Uint64,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_rng_finish(pRngHandle: alc_rng_handle_p) -> alc_error_t;
}
pub const _alc_drbg_type_ALC_DRBG_HMAC: _alc_drbg_type = 0;
pub const _alc_drbg_type_ALC_DRBG_CTR: _alc_drbg_type = 1;
pub type _alc_drbg_type = ::std::os::raw::c_int;
pub use self::_alc_drbg_type as alc_drbg_type_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _alc_hmac_drbg_info {
    pub digest_mode: alc_digest_mode_t,
}
impl Default for _alc_hmac_drbg_info {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type alc_hmac_drbg_info_t = _alc_hmac_drbg_info;
pub type alc_hmac_drbg_info_p = *mut _alc_hmac_drbg_info;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _alc_ctr_drbg_info {
    pub di_keysize: Uint64,
    pub use_derivation_function: bool_,
}
impl Default for _alc_ctr_drbg_info {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type alc_ctr_drbg_info_t = _alc_ctr_drbg_info;
pub type alc_ctr_drbg_info_p = *mut _alc_ctr_drbg_info;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _alc_custom_rng_info {
    pub entropy: *mut Uint8,
    pub entropylen: Uint64,
    pub nonce: *mut Uint8,
    pub noncelen: Uint64,
}
impl Default for _alc_custom_rng_info {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type alc_custom_rng_info_t = _alc_custom_rng_info;
pub type alc_custom_rng_info_p = *mut _alc_custom_rng_info;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct _alc_rng_source_info {
    pub custom_rng: bool_,
    pub di_sourceinfo: _alc_rng_source_info__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union _alc_rng_source_info__bindgen_ty_1 {
    pub rng_info: alc_rng_info_t,
    pub custom_rng_info: alc_custom_rng_info_t,
}
impl Default for _alc_rng_source_info__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for _alc_rng_source_info {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type alc_rng_source_info_t = _alc_rng_source_info;
pub type alc_rng_source_info_p = *mut _alc_rng_source_info;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct _alc_drbg_info_t {
    pub di_type: alc_drbg_type_t,
    pub di_algoinfo: _alc_drbg_info_t__bindgen_ty_1,
    pub di_rng_sourceinfo: alc_rng_source_info_t,
    pub max_entropy_len: Uint64,
    pub max_nonce_len: Uint64,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union _alc_drbg_info_t__bindgen_ty_1 {
    pub hmac_drbg: alc_hmac_drbg_info_t,
    pub ctr_drbg: alc_ctr_drbg_info_t,
}
impl Default for _alc_drbg_info_t__bindgen_ty_1 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for _alc_drbg_info_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type alc_drbg_info_t = _alc_drbg_info_t;
pub type alc_drbg_info_p = *mut _alc_drbg_info_t;
pub type alc_drbg_context_t = ::std::os::raw::c_void;
pub type alc_drbg_context_p = *mut alc_drbg_context_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct alc_drbg_handle {
    pub ch_context: alc_drbg_context_p,
}
impl Default for alc_drbg_handle {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type alc_drbg_handle_t = alc_drbg_handle;
pub type alc_drbg_handle_p = *mut alc_drbg_handle;
pub type AlcDrbgHandle = alc_drbg_handle;
extern "C" {
    pub fn alcp_drbg_supported(pcDrbgInfo: alc_drbg_info_p) -> alc_error_t;
}
extern "C" {
    pub fn alcp_drbg_context_size(pDrbgInfo: alc_drbg_info_p) -> Uint64;
}
extern "C" {
    pub fn alcp_drbg_request(
        pDrbgHandle: alc_drbg_handle_p,
        pDrbgInfo: alc_drbg_info_p,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_drbg_initialize(
        pDrbgHandle: alc_drbg_handle_p,
        cSecurityStrength: ::std::os::raw::c_int,
        personalization_string: *mut Uint8,
        personalization_string_length: Uint64,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_drbg_randomize(
        pDrbgHandle: alc_drbg_handle_p,
        p_Output: *mut Uint8,
        cOutputLength: usize,
        cSecurityStrength: ::std::os::raw::c_int,
        cAdditionalInput: *const Uint8,
        cAdditionalInputLength: usize,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_drbg_finish(pDrbgHandle: alc_drbg_handle_p) -> alc_error_t;
}
pub const alc_ec_curve_id_ALCP_EC_CURVE25519: alc_ec_curve_id = 0;
pub const alc_ec_curve_id_ALCP_EC_SECP256R1: alc_ec_curve_id = 1;
pub const alc_ec_curve_id_ALCP_EC_MAX: alc_ec_curve_id = 2;
pub type alc_ec_curve_id = ::std::os::raw::c_int;
pub const alc_ec_curve_type_ALCP_EC_CURVE_TYPE_SHORT_WEIERSTRASS: alc_ec_curve_type = 0;
pub const alc_ec_curve_type_ALCP_EC_CURVE_TYPE_MONTGOMERY: alc_ec_curve_type = 1;
pub const alc_ec_curve_type_ALCP_EC_CURVE_TYPE_MAX: alc_ec_curve_type = 2;
pub type alc_ec_curve_type = ::std::os::raw::c_int;
pub const alc_ec_point_format_id_ALCP_EC_POINT_FORMAT_UNCOMPRESSED: alc_ec_point_format_id = 0;
pub const alc_ec_point_format_id_ALCP_EC_POINT_FORMAT_COMPRESSED: alc_ec_point_format_id = 1;
pub type alc_ec_point_format_id = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct alc_ec_info {
    pub ecCurveId: alc_ec_curve_id,
    pub ecCurveType: alc_ec_curve_type,
    pub ecPointFormat: alc_ec_point_format_id,
}
impl Default for alc_ec_info {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type alc_ec_info_t = alc_ec_info;
pub type alc_ec_info_p = *mut alc_ec_info;
pub type alc_ec_context_t = ::std::os::raw::c_void;
pub type alc_ec_context_p = *mut alc_ec_context_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _alc_ec_handle {
    pub context: alc_ec_context_p,
}
impl Default for _alc_ec_handle {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type alc_ec_handle_t = _alc_ec_handle;
pub type alc_ec_handle_p = *mut _alc_ec_handle;
pub type AlcEcHandle = _alc_ec_handle;
pub type AlcEcHandleP = *mut _alc_ec_handle;
extern "C" {
    pub fn alcp_ec_context_size(p_ec_info: alc_ec_info_p) -> Uint64;
}
extern "C" {
    pub fn alcp_ec_supported(pEcInfo: alc_ec_info_p) -> alc_error_t;
}
extern "C" {
    pub fn alcp_ec_request(pEcInfo: alc_ec_info_p, pEcHandle: alc_ec_handle_p) -> alc_error_t;
}
extern "C" {
    pub fn alcp_ec_set_privatekey(
        pEcHandle: alc_ec_handle_p,
        pPrivKey: *const Uint8,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_ec_get_publickey(
        pEcHandle: alc_ec_handle_p,
        pPublicKey: *mut Uint8,
        pPrivKey: *const Uint8,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_ec_get_secretkey(
        pEcHandle: alc_ec_handle_p,
        pSecretKey: *mut Uint8,
        pPublicKey: *const Uint8,
        pKeyLength: *mut Uint64,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_ec_finish(pEcHandle: alc_ec_handle_p);
}
extern "C" {
    pub fn alcp_get_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn alcp_get_build_env() -> *const ::std::os::raw::c_char;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _alc_version {
    pub major: ::std::os::raw::c_int,
    pub minor: ::std::os::raw::c_int,
    pub revision: ::std::os::raw::c_uint,
    pub date: *const ::std::os::raw::c_char,
}
impl Default for _alc_version {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type alc_version_t = _alc_version;
pub const alc_rsa_padding_ALCP_RSA_PADDING_OAEP: alc_rsa_padding = 0;
pub const alc_rsa_padding_ALCP_RSA_PADDING_NONE: alc_rsa_padding = 1;
pub type alc_rsa_padding = ::std::os::raw::c_int;
pub const alc_rsa_key_size_KEY_SIZE_1024: alc_rsa_key_size = 1024;
pub const alc_rsa_key_size_KEY_SIZE_2048: alc_rsa_key_size = 2048;
pub const alc_rsa_key_size_KEY_SIZE_UNSUPPORTED: alc_rsa_key_size = 2049;
pub type alc_rsa_key_size = ::std::os::raw::c_int;
pub const DigestIndex_MD_5_SHA_1: DigestIndex = 0;
pub const DigestIndex_MD_5: DigestIndex = 1;
pub const DigestIndex_SHA_1: DigestIndex = 2;
pub const DigestIndex_SHA_224: DigestIndex = 3;
pub const DigestIndex_SHA_256: DigestIndex = 4;
pub const DigestIndex_SHA_384: DigestIndex = 5;
pub const DigestIndex_SHA_512: DigestIndex = 6;
pub const DigestIndex_SHA_512_224: DigestIndex = 7;
pub const DigestIndex_SHA_512_256: DigestIndex = 8;
pub const DigestIndex_SHA_UNKNOWN: DigestIndex = 9;
pub type DigestIndex = ::std::os::raw::c_int;
extern "C" {
    pub static mut DigestInfo: [[Uint8; 19usize]; 9usize];
}
pub type alc_rsa_context_t = ::std::os::raw::c_void;
pub type alc_rsa_context_p = *mut alc_rsa_context_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _alc_rsa_handle {
    pub context: alc_rsa_context_p,
}
impl Default for _alc_rsa_handle {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type alc_rsa_handle_t = _alc_rsa_handle;
pub type alc_rsa_handle_p = *mut _alc_rsa_handle;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct BigNum {
    pub num: *mut Uint64,
    pub size: Uint64,
}
impl Default for BigNum {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
extern "C" {
    pub fn alcp_rsa_get_digest_info_index(mode: alc_digest_mode_t) -> Int32;
}
extern "C" {
    pub fn alcp_rsa_get_digest_info_size(mode: alc_digest_mode_t) -> Int32;
}
extern "C" {
    pub fn alcp_rsa_context_size() -> Uint64;
}
extern "C" {
    pub fn alcp_rsa_request(pRsaHandle: alc_rsa_handle_p) -> alc_error_t;
}
extern "C" {
    pub fn alcp_rsa_publickey_encrypt(
        pRsaHandle: alc_rsa_handle_p,
        pText: *const Uint8,
        textSize: Uint64,
        pEncText: *mut Uint8,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_rsa_publickey_encrypt_oaep(
        pRsaHandle: alc_rsa_handle_p,
        pText: *const Uint8,
        textSize: Uint64,
        label: *const Uint8,
        labelSize: Uint64,
        pSeed: *const Uint8,
        pEncText: *mut Uint8,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_rsa_add_digest(
        pRsaHandle: alc_rsa_handle_p,
        mode: alc_digest_mode_t,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_rsa_add_mgf(pRsaHandle: alc_rsa_handle_p, mode: alc_digest_mode_t) -> alc_error_t;
}
extern "C" {
    pub fn alcp_rsa_privatekey_decrypt(
        pRsaHandle: alc_rsa_handle_p,
        pad: alc_rsa_padding,
        pEncText: *const Uint8,
        encSize: Uint64,
        pText: *mut Uint8,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_rsa_privatekey_decrypt_oaep(
        pRsaHandle: alc_rsa_handle_p,
        pEncText: *const Uint8,
        encSize: Uint64,
        label: *const Uint8,
        labelSize: Uint64,
        pText: *mut Uint8,
        textSize: *mut Uint64,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_rsa_privatekey_sign_pss(
        pRsaHandle: alc_rsa_handle_p,
        check: bool_,
        pText: *const Uint8,
        textSize: Uint64,
        pSalt: *const Uint8,
        saltSize: Uint64,
        pSignedBuff: *mut Uint8,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_rsa_publickey_verify_pss(
        pRsaHandle: alc_rsa_handle_p,
        pText: *const Uint8,
        textSize: Uint64,
        pSignedBuff: *const Uint8,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_rsa_privatekey_sign_pkcs1v15(
        pRsaHandle: alc_rsa_handle_p,
        check: bool_,
        pText: *const Uint8,
        textSize: Uint64,
        pSignedBuff: *mut Uint8,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_rsa_publickey_verify_pkcs1v15(
        pRsaHandle: alc_rsa_handle_p,
        pText: *const Uint8,
        textSize: Uint64,
        pSignedBuff: *const Uint8,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_rsa_privatekey_sign_hash_pkcs1v15(
        pRsaHandle: alc_rsa_handle_p,
        pText: *const Uint8,
        textSize: Uint64,
        pSignedText: *mut Uint8,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_rsa_publickey_verify_hash_pkcs1v15(
        pRsaHandle: alc_rsa_handle_p,
        pText: *const Uint8,
        textSize: Uint64,
        pSignedBuff: *const Uint8,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_rsa_publickey_encrypt_pkcs1v15(
        pRsaHandle: alc_rsa_handle_p,
        pText: *const Uint8,
        textSize: Uint64,
        pEncryptText: *mut Uint8,
        randomPad: *const Uint8,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_rsa_privatekey_decrypt_pkcs1v15(
        pRsaHandle: alc_rsa_handle_p,
        pText: *const Uint8,
        pDecryptText: *mut Uint8,
        textSize: *mut Uint64,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_rsa_privatekey_sign_hash_pss(
        pRsaHandle: alc_rsa_handle_p,
        pHash: *const Uint8,
        hashSize: Uint64,
        pSalt: *const Uint8,
        saltSize: Uint64,
        pSignedBuff: *mut Uint8,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_rsa_publickey_verify_hash_pss(
        pRsaHandle: alc_rsa_handle_p,
        pHash: *const Uint8,
        hashSize: Uint64,
        pSignedBuff: *const Uint8,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_rsa_set_publickey(
        pRsaHandle: alc_rsa_handle_p,
        exponent: Uint64,
        pModulus: *const Uint8,
        size: Uint64,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_rsa_set_bignum_public_key(
        pRsaHandle: alc_rsa_handle_p,
        exponent: *const BigNum,
        pModulus: *const BigNum,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_rsa_set_privatekey(
        pRsaHandle: alc_rsa_handle_p,
        dp: *const Uint8,
        dq: *const Uint8,
        p: *const Uint8,
        q: *const Uint8,
        qinv: *const Uint8,
        mod_: *const Uint8,
        size: Uint64,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_rsa_set_bignum_private_key(
        pRsaHandle: alc_rsa_handle_p,
        dp: *const BigNum,
        dq: *const BigNum,
        p: *const BigNum,
        q: *const BigNum,
        qinv: *const BigNum,
        mod_: *const BigNum,
    ) -> alc_error_t;
}
extern "C" {
    pub fn alcp_rsa_get_key_size(pRsaHandle: alc_rsa_handle_p) -> Uint64;
}
extern "C" {
    pub fn alcp_rsa_finish(pRsaHandle: alc_rsa_handle_p);
}
extern "C" {
    pub fn alcp_rsa_context_copy(
        pSrcHandle: alc_rsa_handle_p,
        pDestHandle: alc_rsa_handle_p,
    ) -> alc_error_t;
}
