/* automatically generated by rust-bindgen 0.69.5 */

pub type rng_int_t = ::std::os::raw::c_int;
pub type rng_uint_t = ::std::os::raw::c_uint;
pub type rng_strlen_t = ::std::os::raw::c_int;
extern "C" {
    pub fn drandinitialize(
        genid: rng_int_t,
        subid: rng_int_t,
        seed: *mut rng_int_t,
        lseed: *mut rng_int_t,
        state: *mut rng_int_t,
        lstate: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandinitialize_(
        genid: *mut rng_int_t,
        subid: *mut rng_int_t,
        seed: *mut rng_int_t,
        lseed: *mut rng_int_t,
        state: *mut rng_int_t,
        lstate: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDINITIALIZE(
        genid: *mut rng_int_t,
        subid: *mut rng_int_t,
        seed: *mut rng_int_t,
        lseed: *mut rng_int_t,
        state: *mut rng_int_t,
        lstate: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandinitialize(
        genid: rng_int_t,
        subid: rng_int_t,
        seed: *mut rng_int_t,
        lseed: *mut rng_int_t,
        state: *mut rng_int_t,
        lstate: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandinitialize_(
        genid: *mut rng_int_t,
        subid: *mut rng_int_t,
        seed: *mut rng_int_t,
        lseed: *mut rng_int_t,
        state: *mut rng_int_t,
        lstate: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDINITIALIZE(
        genid: *mut rng_int_t,
        subid: *mut rng_int_t,
        seed: *mut rng_int_t,
        lseed: *mut rng_int_t,
        state: *mut rng_int_t,
        lstate: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandinitialize_secrng(
        genid: rng_int_t,
        subid: rng_int_t,
        state: *mut rng_int_t,
        lstate: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
pub type RNG_DRANDINITIALIZEUSER_UINI = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut rng_int_t,
        arg2: *mut rng_int_t,
        arg3: *mut rng_int_t,
        arg4: *mut rng_int_t,
        arg5: *mut rng_int_t,
        arg6: *mut rng_int_t,
        arg7: *mut rng_int_t,
    ),
>;
pub type RNG_DRANDINITIALIZEUSER_UGEN = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut rng_int_t,
        arg2: *mut rng_int_t,
        arg3: *mut f64,
        arg4: *mut rng_int_t,
    ),
>;
pub type RNG_SRANDINITIALIZEUSER_UINI = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut rng_int_t,
        arg2: *mut rng_int_t,
        arg3: *mut rng_int_t,
        arg4: *mut rng_int_t,
        arg5: *mut rng_int_t,
        arg6: *mut rng_int_t,
        arg7: *mut rng_int_t,
    ),
>;
pub type RNG_SRANDINITIALIZEUSER_UGEN = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: *mut rng_int_t,
        arg2: *mut rng_int_t,
        arg3: *mut f32,
        arg4: *mut rng_int_t,
    ),
>;
extern "C" {
    pub fn drandinitializeuser(
        uini: RNG_DRANDINITIALIZEUSER_UINI,
        ugen: RNG_DRANDINITIALIZEUSER_UGEN,
        genid: rng_int_t,
        subid: rng_int_t,
        seed: *mut rng_int_t,
        lseed: *mut rng_int_t,
        state: *mut rng_int_t,
        lstate: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandinitializeuser_(
        uini: RNG_DRANDINITIALIZEUSER_UINI,
        ugen: RNG_DRANDINITIALIZEUSER_UGEN,
        genid: rng_int_t,
        subid: rng_int_t,
        seed: *mut rng_int_t,
        lseed: *mut rng_int_t,
        state: *mut rng_int_t,
        lstate: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDINITIALIZEUSER(
        uini: RNG_DRANDINITIALIZEUSER_UINI,
        ugen: RNG_DRANDINITIALIZEUSER_UGEN,
        genid: rng_int_t,
        subid: rng_int_t,
        seed: *mut rng_int_t,
        lseed: *mut rng_int_t,
        state: *mut rng_int_t,
        lstate: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandinitializeuser(
        uini: RNG_SRANDINITIALIZEUSER_UINI,
        ugen: RNG_SRANDINITIALIZEUSER_UGEN,
        genid: rng_int_t,
        subid: rng_int_t,
        seed: *mut rng_int_t,
        lseed: *mut rng_int_t,
        state: *mut rng_int_t,
        lstate: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandinitializeuser_(
        uini: RNG_SRANDINITIALIZEUSER_UINI,
        ugen: RNG_SRANDINITIALIZEUSER_UGEN,
        genid: rng_int_t,
        subid: rng_int_t,
        seed: *mut rng_int_t,
        lseed: *mut rng_int_t,
        state: *mut rng_int_t,
        lstate: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDINITIALIZEUSER(
        uini: RNG_SRANDINITIALIZEUSER_UINI,
        ugen: RNG_SRANDINITIALIZEUSER_UGEN,
        genid: rng_int_t,
        subid: rng_int_t,
        seed: *mut rng_int_t,
        lseed: *mut rng_int_t,
        state: *mut rng_int_t,
        lstate: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandinitializebbs(
        nbits: rng_int_t,
        lp: rng_int_t,
        p: *mut rng_int_t,
        lq: rng_int_t,
        q: *mut rng_int_t,
        ls: rng_int_t,
        s: *mut rng_int_t,
        state: *mut rng_int_t,
        lstate: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandinitializebbs_(
        nbits: *mut rng_int_t,
        lp: *mut rng_int_t,
        p: *mut rng_int_t,
        lq: *mut rng_int_t,
        q: *mut rng_int_t,
        ls: *mut rng_int_t,
        s: *mut rng_int_t,
        state: *mut rng_int_t,
        lstate: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDINITIALIZEBBS(
        nbits: *mut rng_int_t,
        lp: *mut rng_int_t,
        p: *mut rng_int_t,
        lq: *mut rng_int_t,
        q: *mut rng_int_t,
        ls: *mut rng_int_t,
        s: *mut rng_int_t,
        state: *mut rng_int_t,
        lstate: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandinitializebbs(
        nbits: rng_int_t,
        lp: rng_int_t,
        p: *mut rng_int_t,
        lq: rng_int_t,
        q: *mut rng_int_t,
        ls: rng_int_t,
        s: *mut rng_int_t,
        state: *mut rng_int_t,
        lstate: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandinitializebbs_(
        nbits: *mut rng_int_t,
        lp: *mut rng_int_t,
        p: *mut rng_int_t,
        lq: *mut rng_int_t,
        q: *mut rng_int_t,
        ls: *mut rng_int_t,
        s: *mut rng_int_t,
        state: *mut rng_int_t,
        lstate: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDINITIALIZEBBS(
        nbits: *mut rng_int_t,
        lp: *mut rng_int_t,
        p: *mut rng_int_t,
        lq: *mut rng_int_t,
        q: *mut rng_int_t,
        ls: *mut rng_int_t,
        s: *mut rng_int_t,
        state: *mut rng_int_t,
        lstate: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandblumblumshub(
        n: rng_int_t,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandblumblumshub_(
        n: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDBLUMBLUMSHUB(
        n: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandblumblumshub(
        n: rng_int_t,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandblumblumshub_(
        n: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDBLUMBLUMSHUB(
        n: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandbeta(
        n: rng_int_t,
        a: f64,
        b: f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandbeta_(
        n: *mut rng_int_t,
        a: *mut f64,
        b: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDBETA(
        n: *mut rng_int_t,
        a: *mut f64,
        b: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandbeta(
        n: rng_int_t,
        a: f32,
        b: f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandbeta_(
        n: *mut rng_int_t,
        a: *mut f32,
        b: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDBETA(
        n: *mut rng_int_t,
        a: *mut f32,
        b: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandcauchy(
        n: rng_int_t,
        a: f64,
        b: f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandcauchy_(
        n: *mut rng_int_t,
        a: *mut f64,
        b: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDCAUCHY(
        n: *mut rng_int_t,
        a: *mut f64,
        b: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandcauchy(
        n: rng_int_t,
        a: f32,
        b: f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandcauchy_(
        n: *mut rng_int_t,
        a: *mut f32,
        b: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDCAUCHY(
        n: *mut rng_int_t,
        a: *mut f32,
        b: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandchisquared(
        n: rng_int_t,
        df: rng_int_t,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandchisquared_(
        n: *mut rng_int_t,
        df: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDCHISQUARED(
        n: *mut rng_int_t,
        df: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandchisquared(
        n: rng_int_t,
        df: rng_int_t,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandchisquared_(
        n: *mut rng_int_t,
        df: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDCHISQUARED(
        n: *mut rng_int_t,
        df: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandexponential(
        n: rng_int_t,
        a: f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandexponential_(
        n: *mut rng_int_t,
        a: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDEXPONENTIAL(
        n: *mut rng_int_t,
        a: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandexponential(
        n: rng_int_t,
        a: f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandexponential_(
        n: *mut rng_int_t,
        a: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDEXPONENTIAL(
        n: *mut rng_int_t,
        a: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandf(
        n: rng_int_t,
        df1: rng_int_t,
        df2: rng_int_t,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandf_(
        n: *mut rng_int_t,
        df1: *mut rng_int_t,
        df2: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDF(
        n: *mut rng_int_t,
        df1: *mut rng_int_t,
        df2: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandf(
        n: rng_int_t,
        df1: rng_int_t,
        df2: rng_int_t,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandf_(
        n: *mut rng_int_t,
        df1: *mut rng_int_t,
        df2: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDF(
        n: *mut rng_int_t,
        df1: *mut rng_int_t,
        df2: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandgamma(
        n: rng_int_t,
        a: f64,
        b: f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandgamma_(
        n: *mut rng_int_t,
        a: *mut f64,
        b: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDGAMMA(
        n: *mut rng_int_t,
        a: *mut f64,
        b: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandgamma(
        n: rng_int_t,
        a: f32,
        b: f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandgamma_(
        n: *mut rng_int_t,
        a: *mut f32,
        b: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDGAMMA(
        n: *mut rng_int_t,
        a: *mut f32,
        b: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandgaussian(
        n: rng_int_t,
        xmu: f64,
        var: f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandgaussian_(
        n: *mut rng_int_t,
        xmu: *mut f64,
        var: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDGAUSSIAN(
        n: *mut rng_int_t,
        xmu: *mut f64,
        var: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandgaussian(
        n: rng_int_t,
        xmu: f32,
        var: f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandgaussian_(
        n: *mut rng_int_t,
        xmu: *mut f32,
        var: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDGAUSSIAN(
        n: *mut rng_int_t,
        xmu: *mut f32,
        var: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandlogistic(
        n: rng_int_t,
        a: f64,
        b: f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandlogistic_(
        n: *mut rng_int_t,
        a: *mut f64,
        b: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDLOGISTIC(
        n: *mut rng_int_t,
        a: *mut f64,
        b: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandlogistic(
        n: rng_int_t,
        a: f32,
        b: f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandlogistic_(
        n: *mut rng_int_t,
        a: *mut f32,
        b: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDLOGISTIC(
        n: *mut rng_int_t,
        a: *mut f32,
        b: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandlognormal(
        n: rng_int_t,
        xmu: f64,
        var: f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandlognormal_(
        n: *mut rng_int_t,
        xmu: *mut f64,
        var: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDLOGNORMAL(
        n: *mut rng_int_t,
        xmu: *mut f64,
        var: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandlognormal(
        n: rng_int_t,
        xmu: f32,
        var: f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandlognormal_(
        n: *mut rng_int_t,
        xmu: *mut f32,
        var: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDLOGNORMAL(
        n: *mut rng_int_t,
        xmu: *mut f32,
        var: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandstudentst(
        n: rng_int_t,
        df: rng_int_t,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandstudentst_(
        n: *mut rng_int_t,
        df: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDSTUDENTST(
        n: *mut rng_int_t,
        df: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandstudentst(
        n: rng_int_t,
        df: rng_int_t,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandstudentst_(
        n: *mut rng_int_t,
        df: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDSTUDENTST(
        n: *mut rng_int_t,
        df: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandtriangular(
        n: rng_int_t,
        xmin: f64,
        xmed: f64,
        xmax: f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandtriangular_(
        n: *mut rng_int_t,
        xmin: *mut f64,
        xmed: *mut f64,
        xmax: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDTRIANGULAR(
        n: *mut rng_int_t,
        xmin: *mut f64,
        xmed: *mut f64,
        xmax: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandtriangular(
        n: rng_int_t,
        xmin: f32,
        xmed: f32,
        xmax: f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandtriangular_(
        n: *mut rng_int_t,
        xmin: *mut f32,
        xmed: *mut f32,
        xmax: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDTRIANGULAR(
        n: *mut rng_int_t,
        xmin: *mut f32,
        xmed: *mut f32,
        xmax: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn dranduniform(
        n: rng_int_t,
        a: f64,
        b: f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn dranduniform_(
        n: *mut rng_int_t,
        a: *mut f64,
        b: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDUNIFORM(
        n: *mut rng_int_t,
        a: *mut f64,
        b: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn sranduniform(
        n: rng_int_t,
        a: f32,
        b: f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn sranduniform_(
        n: *mut rng_int_t,
        a: *mut f32,
        b: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDUNIFORM(
        n: *mut rng_int_t,
        a: *mut f32,
        b: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandvonmises(
        n: rng_int_t,
        vk: f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandvonmises_(
        n: *mut rng_int_t,
        vk: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDVONMISES(
        n: *mut rng_int_t,
        vk: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandvonmises(
        n: rng_int_t,
        vk: f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandvonmises_(
        n: *mut rng_int_t,
        vk: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDVONMISES(
        n: *mut rng_int_t,
        vk: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandweibull(
        n: rng_int_t,
        a: f64,
        b: f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandweibull_(
        n: *mut rng_int_t,
        a: *mut f64,
        b: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDWEIBULL(
        n: *mut rng_int_t,
        a: *mut f64,
        b: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandweibull(
        n: rng_int_t,
        a: f32,
        b: f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandweibull_(
        n: *mut rng_int_t,
        a: *mut f32,
        b: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDWEIBULL(
        n: *mut rng_int_t,
        a: *mut f32,
        b: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandbinomial(
        n: rng_int_t,
        m: rng_int_t,
        p: f64,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandbinomial_(
        n: *mut rng_int_t,
        m: *mut rng_int_t,
        p: *mut f64,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDBINOMIAL(
        n: *mut rng_int_t,
        m: *mut rng_int_t,
        p: *mut f64,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandbinomial(
        n: rng_int_t,
        m: rng_int_t,
        p: f32,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandbinomial_(
        n: *mut rng_int_t,
        m: *mut rng_int_t,
        p: *mut f32,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDBINOMIAL(
        n: *mut rng_int_t,
        m: *mut rng_int_t,
        p: *mut f32,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandgeometric(
        n: rng_int_t,
        p: f64,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandgeometric_(
        n: *mut rng_int_t,
        p: *mut f64,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDGEOMETRIC(
        n: *mut rng_int_t,
        p: *mut f64,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandgeometric(
        n: rng_int_t,
        p: f32,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandgeometric_(
        n: *mut rng_int_t,
        p: *mut f32,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDGEOMETRIC(
        n: *mut rng_int_t,
        p: *mut f32,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandhypergeometric(
        n: rng_int_t,
        np: rng_int_t,
        ns: rng_int_t,
        m: rng_int_t,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandhypergeometric_(
        n: *mut rng_int_t,
        np: *mut rng_int_t,
        ns: *mut rng_int_t,
        m: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDHYPERGEOMETRIC(
        n: *mut rng_int_t,
        np: *mut rng_int_t,
        ns: *mut rng_int_t,
        m: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandhypergeometric(
        n: rng_int_t,
        np: rng_int_t,
        ns: rng_int_t,
        m: rng_int_t,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandhypergeometric_(
        n: *mut rng_int_t,
        np: *mut rng_int_t,
        ns: *mut rng_int_t,
        m: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDHYPERGEOMETRIC(
        n: *mut rng_int_t,
        np: *mut rng_int_t,
        ns: *mut rng_int_t,
        m: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandnegativebinomial(
        n: rng_int_t,
        m: rng_int_t,
        p: f64,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandnegativebinomial_(
        n: *mut rng_int_t,
        m: *mut rng_int_t,
        p: *mut f64,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDNEGATIVEBINOMIAL(
        n: *mut rng_int_t,
        m: *mut rng_int_t,
        p: *mut f64,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandnegativebinomial(
        n: rng_int_t,
        m: rng_int_t,
        p: f32,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandnegativebinomial_(
        n: *mut rng_int_t,
        m: *mut rng_int_t,
        p: *mut f32,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDNEGATIVEBINOMIAL(
        n: *mut rng_int_t,
        m: *mut rng_int_t,
        p: *mut f32,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandpoisson(
        n: rng_int_t,
        lambda: f64,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandpoisson_(
        n: *mut rng_int_t,
        lambda: *mut f64,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDPOISSON(
        n: *mut rng_int_t,
        lambda: *mut f64,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandpoisson(
        n: rng_int_t,
        lambda: f32,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandpoisson_(
        n: *mut rng_int_t,
        lambda: *mut f32,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDPOISSON(
        n: *mut rng_int_t,
        lambda: *mut f32,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn dranddiscreteuniform(
        n: rng_int_t,
        a: rng_int_t,
        b: rng_int_t,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn dranddiscreteuniform_(
        n: *mut rng_int_t,
        a: *mut rng_int_t,
        b: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDDISCRETEUNIFORM(
        n: *mut rng_int_t,
        a: *mut rng_int_t,
        b: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn sranddiscreteuniform(
        n: rng_int_t,
        a: rng_int_t,
        b: rng_int_t,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn sranddiscreteuniform_(
        n: *mut rng_int_t,
        a: *mut rng_int_t,
        b: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDDISCRETEUNIFORM(
        n: *mut rng_int_t,
        a: *mut rng_int_t,
        b: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandgeneraldiscrete(
        n: rng_int_t,
        ref_: *mut f64,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandgeneraldiscrete_(
        n: *mut rng_int_t,
        ref_: *mut f64,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDGENERALDISCRETE(
        n: *mut rng_int_t,
        ref_: *mut f64,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandgeneraldiscrete(
        n: rng_int_t,
        ref_: *mut f32,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandgeneraldiscrete_(
        n: *mut rng_int_t,
        ref_: *mut f32,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDGENERALDISCRETE(
        n: *mut rng_int_t,
        ref_: *mut f32,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandbinomialreference(
        m: rng_int_t,
        p: f64,
        ref_: *mut f64,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandbinomialreference_(
        m: *mut rng_int_t,
        p: *mut f64,
        ref_: *mut f64,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDBINOMIALREFERENCE(
        m: *mut rng_int_t,
        p: *mut f64,
        ref_: *mut f64,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandbinomialreference(
        m: rng_int_t,
        p: f32,
        ref_: *mut f32,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandbinomialreference_(
        m: *mut rng_int_t,
        p: *mut f32,
        ref_: *mut f32,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDBINOMIALREFERENCE(
        m: *mut rng_int_t,
        p: *mut f32,
        ref_: *mut f32,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandgeometricreference(
        p: f64,
        ref_: *mut f64,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandgeometricreference_(
        p: *mut f64,
        ref_: *mut f64,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDGEOMETRICREFERENCE(
        p: *mut f64,
        ref_: *mut f64,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandgeometricreference(
        p: f32,
        ref_: *mut f32,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandgeometricreference_(
        p: *mut f32,
        ref_: *mut f32,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDGEOMETRICREFERENCE(
        p: *mut f32,
        ref_: *mut f32,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandhypergeometricreference(
        np: rng_int_t,
        ns: rng_int_t,
        m: rng_int_t,
        ref_: *mut f64,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandhypergeometricreference_(
        np: *mut rng_int_t,
        ns: *mut rng_int_t,
        m: *mut rng_int_t,
        ref_: *mut f64,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDHYPERGEOMETRICREFERENCE(
        np: *mut rng_int_t,
        ns: *mut rng_int_t,
        m: *mut rng_int_t,
        ref_: *mut f64,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandhypergeometricreference(
        np: rng_int_t,
        ns: rng_int_t,
        m: rng_int_t,
        ref_: *mut f32,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandhypergeometricreference_(
        np: *mut rng_int_t,
        ns: *mut rng_int_t,
        m: *mut rng_int_t,
        ref_: *mut f32,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDHYPERGEOMETRICREFERENCE(
        np: *mut rng_int_t,
        ns: *mut rng_int_t,
        m: *mut rng_int_t,
        ref_: *mut f32,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandnegativebinomialreference(
        m: rng_int_t,
        p: f64,
        ref_: *mut f64,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandnegativebinomialreference_(
        m: *mut rng_int_t,
        p: f64,
        ref_: *mut f64,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDNEGATIVEBINOMIALREFERENCE(
        m: *mut rng_int_t,
        p: *mut f64,
        ref_: *mut f64,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandnegativebinomialreference(
        m: rng_int_t,
        p: f32,
        ref_: *mut f32,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandnegativebinomialreference_(
        m: *mut rng_int_t,
        p: *mut f32,
        ref_: *mut f32,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDNEGATIVEBINOMIALREFERENCE(
        m: *mut rng_int_t,
        p: *mut f32,
        ref_: *mut f32,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandpoissonreference(
        lambda: f64,
        ref_: *mut f64,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandpoissonreference_(
        lambda: *mut f64,
        ref_: *mut f64,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDPOISSONREFERENCE(
        lambda: *mut f64,
        ref_: *mut f64,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandpoissonreference(
        lambda: f32,
        ref_: *mut f32,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandpoissonreference_(
        lambda: *mut f32,
        ref_: *mut f32,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDPOISSONREFERENCE(
        lambda: *mut f32,
        ref_: *mut f32,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandmultinormal(
        n: rng_int_t,
        m: rng_int_t,
        xmu: *mut f64,
        c: *mut f64,
        ldc: rng_int_t,
        state: *mut rng_int_t,
        x: *mut f64,
        ldx: rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandmultinormal_(
        n: *mut rng_int_t,
        m: *mut rng_int_t,
        xmu: *mut f64,
        c: *mut f64,
        ldc: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut f64,
        ldx: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDMULTINORMAL(
        n: *mut rng_int_t,
        m: *mut rng_int_t,
        xmu: *mut f64,
        c: *mut f64,
        ldc: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut f64,
        ldx: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandmultinormal(
        n: rng_int_t,
        m: rng_int_t,
        xmu: *mut f32,
        c: *mut f32,
        ldc: rng_int_t,
        state: *mut rng_int_t,
        x: *mut f32,
        ldx: rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandmultinormal_(
        n: *mut rng_int_t,
        m: *mut rng_int_t,
        xmu: *mut f32,
        c: *mut f32,
        ldc: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut f32,
        ldx: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDMULTINORMAL(
        n: *mut rng_int_t,
        m: *mut rng_int_t,
        xmu: *mut f32,
        c: *mut f32,
        ldc: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut f32,
        ldx: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandmultistudentst(
        n: rng_int_t,
        m: rng_int_t,
        df: rng_int_t,
        xmu: *mut f64,
        c: *mut f64,
        ldc: rng_int_t,
        state: *mut rng_int_t,
        x: *mut f64,
        ldx: rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandmultistudentst_(
        n: *mut rng_int_t,
        m: *mut rng_int_t,
        df: *mut rng_int_t,
        xmu: *mut f64,
        c: *mut f64,
        ldc: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut f64,
        ldx: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDMULTISTUDENTST(
        n: *mut rng_int_t,
        m: *mut rng_int_t,
        df: *mut rng_int_t,
        xmu: *mut f64,
        c: *mut f64,
        ldc: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut f64,
        ldx: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandmultistudentst(
        n: rng_int_t,
        m: rng_int_t,
        df: rng_int_t,
        xmu: *mut f32,
        c: *mut f32,
        ldc: rng_int_t,
        state: *mut rng_int_t,
        x: *mut f32,
        ldx: rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandmultistudentst_(
        n: *mut rng_int_t,
        m: *mut rng_int_t,
        df: *mut rng_int_t,
        xmu: *mut f32,
        c: *mut f32,
        ldc: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut f32,
        ldx: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDMULTISTUDENTST(
        n: *mut rng_int_t,
        m: *mut rng_int_t,
        df: *mut rng_int_t,
        xmu: *mut f32,
        c: *mut f32,
        ldc: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut f32,
        ldx: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandmultinormalreference(
        m: rng_int_t,
        xmu: *mut f64,
        c: *mut f64,
        ldc: rng_int_t,
        ref_: *mut f64,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandmultinormalreference_(
        m: *mut rng_int_t,
        xmu: *mut f64,
        c: *mut f64,
        ldc: *mut rng_int_t,
        ref_: *mut f64,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDMULTINORMALREFERENCE(
        m: *mut rng_int_t,
        xmu: *mut f64,
        c: *mut f64,
        ldc: *mut rng_int_t,
        ref_: *mut f64,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandmultinormalreference(
        m: rng_int_t,
        xmu: *mut f32,
        c: *mut f32,
        ldc: rng_int_t,
        ref_: *mut f32,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandmultinormalreference_(
        m: *mut rng_int_t,
        xmu: *mut f32,
        c: *mut f32,
        ldc: *mut rng_int_t,
        ref_: *mut f32,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDMULTINORMALREFERENCE(
        m: *mut rng_int_t,
        xmu: *mut f32,
        c: *mut f32,
        ldc: *mut rng_int_t,
        ref_: *mut f32,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandmultinormalr(
        n: rng_int_t,
        ref_: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        ldx: rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandmultinormalr_(
        n: *mut rng_int_t,
        ref_: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        ldx: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDMULTINORMALR(
        n: *mut rng_int_t,
        ref_: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        ldx: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandmultinormalr(
        n: rng_int_t,
        ref_: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        ldx: rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandmultinormalr_(
        n: *mut rng_int_t,
        ref_: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        ldx: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDMULTINORMALR(
        n: *mut rng_int_t,
        ref_: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        ldx: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandmultistudentstreference(
        m: rng_int_t,
        df: rng_int_t,
        xmu: *mut f64,
        c: *mut f64,
        ldc: rng_int_t,
        ref_: *mut f64,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandmultistudentstreference_(
        m: *mut rng_int_t,
        df: *mut rng_int_t,
        xmu: *mut f64,
        c: *mut f64,
        ldc: *mut rng_int_t,
        ref_: *mut f64,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDMULTISTUDENTSTREFERENCE(
        m: *mut rng_int_t,
        df: *mut rng_int_t,
        xmu: *mut f64,
        c: *mut f64,
        ldc: *mut rng_int_t,
        ref_: *mut f64,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandmultistudentstreference(
        m: rng_int_t,
        df: rng_int_t,
        xmu: *mut f32,
        c: *mut f32,
        ldc: rng_int_t,
        ref_: *mut f32,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandmultistudentstreference_(
        m: *mut rng_int_t,
        df: *mut rng_int_t,
        xmu: *mut f32,
        c: *mut f32,
        ldc: *mut rng_int_t,
        ref_: *mut f32,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDMULTISTUDENTSTREFERENCE(
        m: *mut rng_int_t,
        df: *mut rng_int_t,
        xmu: *mut f32,
        c: *mut f32,
        ldc: *mut rng_int_t,
        ref_: *mut f32,
        lref: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandmultistudentstr(
        n: rng_int_t,
        ref_: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        ldx: rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandmultistudentstr_(
        n: *mut rng_int_t,
        ref_: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        ldx: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDMULTISTUDENTSTR(
        n: *mut rng_int_t,
        ref_: *mut f64,
        state: *mut rng_int_t,
        x: *mut f64,
        ldx: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandmultistudentstr(
        n: rng_int_t,
        ref_: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        ldx: rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandmultistudentstr_(
        n: *mut rng_int_t,
        ref_: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        ldx: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDMULTISTUDENTSTR(
        n: *mut rng_int_t,
        ref_: *mut f32,
        state: *mut rng_int_t,
        x: *mut f32,
        ldx: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandmultinomial(
        n: rng_int_t,
        m: rng_int_t,
        p: *mut f64,
        k: rng_int_t,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        ldx: rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandmultinomial_(
        n: *mut rng_int_t,
        m: *mut rng_int_t,
        p: *mut f64,
        k: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        ldx: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDMULTINOMIAL(
        n: *mut rng_int_t,
        m: *mut rng_int_t,
        p: *mut f64,
        k: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        ldx: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandmultinomial(
        n: rng_int_t,
        m: rng_int_t,
        p: *mut f32,
        k: rng_int_t,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        ldx: rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandmultinomial_(
        n: *mut rng_int_t,
        m: *mut rng_int_t,
        p: *mut f32,
        k: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        ldx: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDMULTINOMIAL(
        n: *mut rng_int_t,
        m: *mut rng_int_t,
        p: *mut f32,
        k: *mut rng_int_t,
        state: *mut rng_int_t,
        x: *mut rng_int_t,
        ldx: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn drandskipahead(n: rng_int_t, state: *mut rng_int_t, info: *mut rng_int_t);
}
extern "C" {
    pub fn drandskipahead_(n: *mut rng_int_t, state: *mut rng_int_t, info: *mut rng_int_t);
}
extern "C" {
    pub fn DRANDSKIPAHEAD(n: *mut rng_int_t, state: *mut rng_int_t, info: *mut rng_int_t);
}
extern "C" {
    pub fn srandskipahead(n: rng_int_t, state: *mut rng_int_t, info: *mut rng_int_t);
}
extern "C" {
    pub fn srandskipahead_(n: *mut rng_int_t, state: *mut rng_int_t, info: *mut rng_int_t);
}
extern "C" {
    pub fn SRANDSKIPAHEAD(n: *mut rng_int_t, state: *mut rng_int_t, info: *mut rng_int_t);
}
extern "C" {
    pub fn drandleapfrog(n: rng_int_t, k: rng_int_t, state: *mut rng_int_t, info: *mut rng_int_t);
}
extern "C" {
    pub fn drandleapfrog_(
        n: *mut rng_int_t,
        k: *mut rng_int_t,
        state: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn DRANDLEAPFROG(
        n: *mut rng_int_t,
        k: *mut rng_int_t,
        state: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn srandleapfrog(n: rng_int_t, k: rng_int_t, state: *mut rng_int_t, info: *mut rng_int_t);
}
extern "C" {
    pub fn srandleapfrog_(
        n: *mut rng_int_t,
        k: *mut rng_int_t,
        state: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn SRANDLEAPFROG(
        n: *mut rng_int_t,
        k: *mut rng_int_t,
        state: *mut rng_int_t,
        info: *mut rng_int_t,
    );
}
extern "C" {
    pub fn get_rngversion() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn get_rngversion_() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn GET_RNGVERSION() -> *const ::std::os::raw::c_char;
}
