/* automatically generated by rust-bindgen 0.69.5 */

pub const AOCL_COMPRESSION_LIBRARY_VERSION: &[u8; 23] = b"AOCL-Compression 5.1.0\0";
pub const INTERNAL_LIBRARY_VERSION: &[u8; 35] = b"AOCL LOSSLESS DATA COMPRESSION 3.0\0";
pub const LZ4_FREESTANDING: u32 = 0;
pub const LZ4_VERSION_MAJOR: u32 = 1;
pub const LZ4_VERSION_MINOR: u32 = 9;
pub const LZ4_VERSION_RELEASE: u32 = 4;
pub const LZ4_VERSION_NUMBER: u32 = 10904;
pub const LZ4_MEMORY_USAGE_MIN: u32 = 10;
pub const LZ4_MEMORY_USAGE_DEFAULT: u32 = 14;
pub const LZ4_MEMORY_USAGE_MAX: u32 = 20;
pub const LZ4_MEMORY_USAGE: u32 = 14;
pub const LZ4_MAX_INPUT_SIZE: u32 = 2113929216;
pub const LZ4_HASHLOG: u32 = 12;
pub const LZ4_HASHTABLESIZE: u32 = 16384;
pub const LZ4_HASH_SIZE_U32: u32 = 4096;
pub const LZ4_STREAM_MINSIZE: u32 = 16416;
pub const LZ4_STREAMDECODE_MINSIZE: u32 = 32;
pub const LZ4HC_CLEVEL_MIN: u32 = 3;
pub const LZ4HC_CLEVEL_DEFAULT: u32 = 9;
pub const LZ4HC_CLEVEL_OPT_MIN: u32 = 10;
pub const LZ4HC_CLEVEL_MAX: u32 = 12;
pub const LZ4HC_DICTIONARY_LOGSIZE: u32 = 16;
pub const LZ4HC_MAXD: u32 = 65536;
pub const LZ4HC_MAXD_MASK: u32 = 65535;
pub const LZ4HC_HASH_LOG: u32 = 15;
pub const LZ4HC_HASHTABLESIZE: u32 = 32768;
pub const LZ4HC_HASH_MASK: u32 = 32767;
pub const HASH_CHAIN_ALLOC: u32 = 128;
pub const CF_HC_CHAIN_TABLE_SZ: u32 = 4194304;
pub const CF_HC_HASH_TABLE_SZ: u32 = 0;
pub const AOCL_LZ4HC_HASHTABLESIZE: u32 = 0;
pub const AOCL_LZ4HC_MAXD: u32 = 4194304;
pub const LZ4_STREAMHC_MINSIZE: u32 = 262200;
pub const LZ4F_VERSION: u32 = 100;
pub const LZ4F_HEADER_SIZE_MIN: u32 = 7;
pub const LZ4F_HEADER_SIZE_MAX: u32 = 19;
pub const LZ4F_BLOCK_HEADER_SIZE: u32 = 4;
pub const LZ4F_BLOCK_CHECKSUM_SIZE: u32 = 4;
pub const LZ4F_CONTENT_CHECKSUM_SIZE: u32 = 4;
pub const LZ4F_MAGICNUMBER: u32 = 407708164;
pub const LZ4F_MAGIC_SKIPPABLE_START: u32 = 407710288;
pub const LZ4F_MIN_SIZE_TO_KNOW_HEADER_LENGTH: u32 = 5;
pub const BZ_RUN: u32 = 0;
pub const BZ_FLUSH: u32 = 1;
pub const BZ_FINISH: u32 = 2;
pub const BZ_OK: u32 = 0;
pub const BZ_RUN_OK: u32 = 1;
pub const BZ_FLUSH_OK: u32 = 2;
pub const BZ_FINISH_OK: u32 = 3;
pub const BZ_STREAM_END: u32 = 4;
pub const BZ_SEQUENCE_ERROR: i32 = -1;
pub const BZ_PARAM_ERROR: i32 = -2;
pub const BZ_MEM_ERROR: i32 = -3;
pub const BZ_DATA_ERROR: i32 = -4;
pub const BZ_DATA_ERROR_MAGIC: i32 = -5;
pub const BZ_IO_ERROR: i32 = -6;
pub const BZ_UNEXPECTED_EOF: i32 = -7;
pub const BZ_OUTBUFF_FULL: i32 = -8;
pub const BZ_CONFIG_ERROR: i32 = -9;
pub const BZ_MAX_UNUSED: u32 = 5000;
pub const SZ_OK: u32 = 0;
pub const SZ_ERROR_DATA: u32 = 1;
pub const SZ_ERROR_MEM: u32 = 2;
pub const SZ_ERROR_CRC: u32 = 3;
pub const SZ_ERROR_UNSUPPORTED: u32 = 4;
pub const SZ_ERROR_PARAM: u32 = 5;
pub const SZ_ERROR_INPUT_EOF: u32 = 6;
pub const SZ_ERROR_OUTPUT_EOF: u32 = 7;
pub const SZ_ERROR_READ: u32 = 8;
pub const SZ_ERROR_WRITE: u32 = 9;
pub const SZ_ERROR_PROGRESS: u32 = 10;
pub const SZ_ERROR_FAIL: u32 = 11;
pub const SZ_ERROR_THREAD: u32 = 12;
pub const SZ_ERROR_ARCHIVE: u32 = 16;
pub const SZ_ERROR_NO_ARCHIVE: u32 = 17;
pub const True: u32 = 1;
pub const False: u32 = 0;
pub const CHAR_PATH_SEPARATOR: u8 = 92u8;
pub const WCHAR_PATH_SEPARATOR: u8 = 92u8;
pub const STRING_PATH_SEPARATOR: &[u8; 2] = b"\\\0";
pub const WSTRING_PATH_SEPARATOR: &[u8; 2] = b"\\\0";
pub const k_PropVar_TimePrec_0: u32 = 0;
pub const k_PropVar_TimePrec_Unix: u32 = 1;
pub const k_PropVar_TimePrec_DOS: u32 = 2;
pub const k_PropVar_TimePrec_HighPrec: u32 = 3;
pub const k_PropVar_TimePrec_Base: u32 = 16;
pub const k_PropVar_TimePrec_100ns: u32 = 23;
pub const k_PropVar_TimePrec_1ns: u32 = 25;
pub const LZMA_PROPS_SIZE: u32 = 5;
pub const LZMA_REQUIRED_INPUT_MAX: u32 = 20;
pub const aocl_error_type_ERR_MEMORY_ALLOC: aocl_error_type = -6;
pub const aocl_error_type_ERR_INVALID_INPUT: aocl_error_type = -5;
pub const aocl_error_type_ERR_UNSUPPORTED_METHOD: aocl_error_type = -4;
pub const aocl_error_type_ERR_EXCLUDED_METHOD: aocl_error_type = -3;
pub const aocl_error_type_ERR_COMPRESSION_FAILED: aocl_error_type = -2;
pub const aocl_error_type_ERR_COMPRESSION_INVALID_OUTPUT: aocl_error_type = -1;
pub type aocl_error_type = ::std::os::raw::c_int;
pub const aocl_compression_type_LZ4: aocl_compression_type = 0;
pub const aocl_compression_type_LZ4HC: aocl_compression_type = 1;
pub const aocl_compression_type_LZMA: aocl_compression_type = 2;
pub const aocl_compression_type_BZIP2: aocl_compression_type = 3;
pub const aocl_compression_type_SNAPPY: aocl_compression_type = 4;
pub const aocl_compression_type_ZLIB: aocl_compression_type = 5;
pub const aocl_compression_type_ZSTD: aocl_compression_type = 6;
pub const aocl_compression_type_AOCL_COMPRESSOR_ALGOS_NUM: aocl_compression_type = 7;
pub type aocl_compression_type = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct aocl_compression_desc {
    pub inBuf: *mut ::std::os::raw::c_char,
    pub outBuf: *mut ::std::os::raw::c_char,
    pub workBuf: *mut ::std::os::raw::c_char,
    pub inSize: usize,
    pub outSize: usize,
    pub level: usize,
    pub optVar: usize,
    pub numThreads: ::std::os::raw::c_int,
    pub numMPIranks: ::std::os::raw::c_int,
    pub memLimit: usize,
    pub measureStats: ::std::os::raw::c_int,
    pub cSize: u64,
    pub dSize: u64,
    pub cTime: u64,
    pub dTime: u64,
    pub cSpeed: f32,
    pub dSpeed: f32,
    pub optOff: ::std::os::raw::c_int,
    pub optLevel: ::std::os::raw::c_int,
}
impl Default for aocl_compression_desc {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
extern "C" {
    pub fn aocl_llc_compressBound(codec_type: aocl_compression_type, inSize: usize) -> i64;
}
extern "C" {
    pub fn aocl_llc_compress(
        handle: *mut aocl_compression_desc,
        codec_type: aocl_compression_type,
    ) -> i64;
}
extern "C" {
    pub fn aocl_llc_decompress(
        handle: *mut aocl_compression_desc,
        codec_type: aocl_compression_type,
    ) -> i64;
}
extern "C" {
    pub fn aocl_llc_setup(
        handle: *mut aocl_compression_desc,
        codec_type: aocl_compression_type,
    ) -> i32;
}
extern "C" {
    pub fn aocl_llc_destroy(handle: *mut aocl_compression_desc, codec_type: aocl_compression_type);
}
extern "C" {
    pub fn aocl_llc_version() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn aocl_llc_skip_rap_frame(src: *mut ::std::os::raw::c_char, src_size: i32) -> i32;
}
extern "C" {
    pub fn LZ4_versionNumber() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_versionString() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn LZ4_compress_default(
        src: *const ::std::os::raw::c_char,
        dst: *mut ::std::os::raw::c_char,
        srcSize: ::std::os::raw::c_int,
        dstCapacity: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_decompress_safe(
        src: *const ::std::os::raw::c_char,
        dst: *mut ::std::os::raw::c_char,
        compressedSize: ::std::os::raw::c_int,
        dstCapacity: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_compressBound(inputSize: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_compress_fast(
        src: *const ::std::os::raw::c_char,
        dst: *mut ::std::os::raw::c_char,
        srcSize: ::std::os::raw::c_int,
        dstCapacity: ::std::os::raw::c_int,
        acceleration: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_sizeofState() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_compress_fast_extState(
        state: *mut ::std::os::raw::c_void,
        src: *const ::std::os::raw::c_char,
        dst: *mut ::std::os::raw::c_char,
        srcSize: ::std::os::raw::c_int,
        dstCapacity: ::std::os::raw::c_int,
        acceleration: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_compress_destSize(
        src: *const ::std::os::raw::c_char,
        dst: *mut ::std::os::raw::c_char,
        srcSizePtr: *mut ::std::os::raw::c_int,
        targetDstSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_decompress_safe_partial(
        src: *const ::std::os::raw::c_char,
        dst: *mut ::std::os::raw::c_char,
        srcSize: ::std::os::raw::c_int,
        targetOutputSize: ::std::os::raw::c_int,
        dstCapacity: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn aocl_setup_lz4(
        optOff: ::std::os::raw::c_int,
        optLevel: ::std::os::raw::c_int,
        insize: usize,
        level: usize,
        windowLog: usize,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn aocl_destroy_lz4();
}
pub type LZ4_stream_t = LZ4_stream_u;
extern "C" {
    pub fn LZ4_createStream() -> *mut LZ4_stream_t;
}
extern "C" {
    pub fn LZ4_freeStream(streamPtr: *mut LZ4_stream_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_resetStream_fast(streamPtr: *mut LZ4_stream_t);
}
extern "C" {
    pub fn LZ4_loadDict(
        streamPtr: *mut LZ4_stream_t,
        dictionary: *const ::std::os::raw::c_char,
        dictSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_compress_fast_continue(
        streamPtr: *mut LZ4_stream_t,
        src: *const ::std::os::raw::c_char,
        dst: *mut ::std::os::raw::c_char,
        srcSize: ::std::os::raw::c_int,
        dstCapacity: ::std::os::raw::c_int,
        acceleration: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_saveDict(
        streamPtr: *mut LZ4_stream_t,
        safeBuffer: *mut ::std::os::raw::c_char,
        maxDictSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
pub type LZ4_streamDecode_t = LZ4_streamDecode_u;
extern "C" {
    pub fn LZ4_createStreamDecode() -> *mut LZ4_streamDecode_t;
}
extern "C" {
    pub fn LZ4_freeStreamDecode(LZ4_stream: *mut LZ4_streamDecode_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_setStreamDecode(
        LZ4_streamDecode: *mut LZ4_streamDecode_t,
        dictionary: *const ::std::os::raw::c_char,
        dictSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_decoderRingBufferSize(maxBlockSize: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_decompress_safe_continue(
        LZ4_streamDecode: *mut LZ4_streamDecode_t,
        src: *const ::std::os::raw::c_char,
        dst: *mut ::std::os::raw::c_char,
        srcSize: ::std::os::raw::c_int,
        dstCapacity: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_decompress_safe_usingDict(
        src: *const ::std::os::raw::c_char,
        dst: *mut ::std::os::raw::c_char,
        srcSize: ::std::os::raw::c_int,
        dstCapacity: ::std::os::raw::c_int,
        dictStart: *const ::std::os::raw::c_char,
        dictSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_decompress_safe_partial_usingDict(
        src: *const ::std::os::raw::c_char,
        dst: *mut ::std::os::raw::c_char,
        compressedSize: ::std::os::raw::c_int,
        targetOutputSize: ::std::os::raw::c_int,
        maxOutputSize: ::std::os::raw::c_int,
        dictStart: *const ::std::os::raw::c_char,
        dictSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
pub type LZ4_i8 = i8;
pub type LZ4_byte = u8;
pub type LZ4_u16 = u16;
pub type LZ4_u32 = u32;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct LZ4_stream_t_internal {
    pub _address: u8,
}
#[repr(C)]
#[repr(align(8))]
#[derive(Copy, Clone)]
pub union LZ4_stream_u {
    pub _address: u8,
}
impl Default for LZ4_stream_u {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
extern "C" {
    pub fn LZ4_initStream(buffer: *mut ::std::os::raw::c_void, size: usize) -> *mut LZ4_stream_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LZ4_streamDecode_t_internal {
    pub externalDict: *const LZ4_byte,
    pub prefixEnd: *const LZ4_byte,
    pub extDictSize: usize,
    pub prefixSize: usize,
}
impl Default for LZ4_streamDecode_t_internal {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[repr(align(8))]
#[derive(Copy, Clone)]
pub union LZ4_streamDecode_u {
    pub _address: u8,
}
impl Default for LZ4_streamDecode_u {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
extern "C" {
    pub fn LZ4_compress(
        src: *const ::std::os::raw::c_char,
        dest: *mut ::std::os::raw::c_char,
        srcSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_compress_limitedOutput(
        src: *const ::std::os::raw::c_char,
        dest: *mut ::std::os::raw::c_char,
        srcSize: ::std::os::raw::c_int,
        maxOutputSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_compress_withState(
        state: *mut ::std::os::raw::c_void,
        source: *const ::std::os::raw::c_char,
        dest: *mut ::std::os::raw::c_char,
        inputSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_compress_limitedOutput_withState(
        state: *mut ::std::os::raw::c_void,
        source: *const ::std::os::raw::c_char,
        dest: *mut ::std::os::raw::c_char,
        inputSize: ::std::os::raw::c_int,
        maxOutputSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_compress_continue(
        LZ4_streamPtr: *mut LZ4_stream_t,
        source: *const ::std::os::raw::c_char,
        dest: *mut ::std::os::raw::c_char,
        inputSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_compress_limitedOutput_continue(
        LZ4_streamPtr: *mut LZ4_stream_t,
        source: *const ::std::os::raw::c_char,
        dest: *mut ::std::os::raw::c_char,
        inputSize: ::std::os::raw::c_int,
        maxOutputSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_uncompress(
        source: *const ::std::os::raw::c_char,
        dest: *mut ::std::os::raw::c_char,
        outputSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_uncompress_unknownOutputSize(
        source: *const ::std::os::raw::c_char,
        dest: *mut ::std::os::raw::c_char,
        isize_: ::std::os::raw::c_int,
        maxOutputSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_create(inputBuffer: *mut ::std::os::raw::c_char) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn LZ4_sizeofStreamState() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_resetStreamState(
        state: *mut ::std::os::raw::c_void,
        inputBuffer: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_slideInputBuffer(state: *mut ::std::os::raw::c_void) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn LZ4_decompress_safe_withPrefix64k(
        src: *const ::std::os::raw::c_char,
        dst: *mut ::std::os::raw::c_char,
        compressedSize: ::std::os::raw::c_int,
        maxDstSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_decompress_fast_withPrefix64k(
        src: *const ::std::os::raw::c_char,
        dst: *mut ::std::os::raw::c_char,
        originalSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_decompress_fast(
        src: *const ::std::os::raw::c_char,
        dst: *mut ::std::os::raw::c_char,
        originalSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_decompress_fast_continue(
        LZ4_streamDecode: *mut LZ4_streamDecode_t,
        src: *const ::std::os::raw::c_char,
        dst: *mut ::std::os::raw::c_char,
        originalSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_decompress_fast_usingDict(
        src: *const ::std::os::raw::c_char,
        dst: *mut ::std::os::raw::c_char,
        originalSize: ::std::os::raw::c_int,
        dictStart: *const ::std::os::raw::c_char,
        dictSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_resetStream(streamPtr: *mut LZ4_stream_t);
}
extern "C" {
    pub fn LZ4_compress_HC(
        src: *const ::std::os::raw::c_char,
        dst: *mut ::std::os::raw::c_char,
        srcSize: ::std::os::raw::c_int,
        dstCapacity: ::std::os::raw::c_int,
        compressionLevel: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_sizeofStateHC() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn AOCL_LZ4_sizeofStateHC() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_compress_HC_extStateHC(
        stateHC: *mut ::std::os::raw::c_void,
        src: *const ::std::os::raw::c_char,
        dst: *mut ::std::os::raw::c_char,
        srcSize: ::std::os::raw::c_int,
        maxDstSize: ::std::os::raw::c_int,
        compressionLevel: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_compress_HC_destSize(
        stateHC: *mut ::std::os::raw::c_void,
        src: *const ::std::os::raw::c_char,
        dst: *mut ::std::os::raw::c_char,
        srcSizePtr: *mut ::std::os::raw::c_int,
        targetDstSize: ::std::os::raw::c_int,
        compressionLevel: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn aocl_setup_lz4hc(
        optOff: ::std::os::raw::c_int,
        optLevel: ::std::os::raw::c_int,
        insize: usize,
        level: usize,
        windowLog: usize,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn aocl_destroy_lz4hc();
}
pub type LZ4_streamHC_t = LZ4_streamHC_u;
pub type AOCL_LZ4_streamHC_t = AOCL_LZ4_streamHC_u;
extern "C" {
    pub fn LZ4_createStreamHC() -> *mut LZ4_streamHC_t;
}
extern "C" {
    pub fn AOCL_LZ4_createStreamHC() -> *mut AOCL_LZ4_streamHC_t;
}
extern "C" {
    pub fn LZ4_freeStreamHC(streamHCPtr: *mut LZ4_streamHC_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn AOCL_LZ4_freeStreamHC(streamHCPtr: *mut AOCL_LZ4_streamHC_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_resetStreamHC_fast(
        streamHCPtr: *mut LZ4_streamHC_t,
        compressionLevel: ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn AOCL_LZ4_resetStreamHC_fast(
        streamHCPtr: *mut AOCL_LZ4_streamHC_t,
        compressionLevel: ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn LZ4_loadDictHC(
        streamHCPtr: *mut LZ4_streamHC_t,
        dictionary: *const ::std::os::raw::c_char,
        dictSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_compress_HC_continue(
        streamHCPtr: *mut LZ4_streamHC_t,
        src: *const ::std::os::raw::c_char,
        dst: *mut ::std::os::raw::c_char,
        srcSize: ::std::os::raw::c_int,
        maxDstSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_compress_HC_continue_destSize(
        LZ4_streamHCPtr: *mut LZ4_streamHC_t,
        src: *const ::std::os::raw::c_char,
        dst: *mut ::std::os::raw::c_char,
        srcSizePtr: *mut ::std::os::raw::c_int,
        targetDstSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_saveDictHC(
        streamHCPtr: *mut LZ4_streamHC_t,
        safeBuffer: *mut ::std::os::raw::c_char,
        maxDictSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct LZ4HC_CCtx_internal {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct AOCL_LZ4HC_CCtx_internal {
    pub _address: u8,
}
#[repr(C)]
#[repr(align(8))]
#[derive(Copy, Clone)]
pub union LZ4_streamHC_u {
    pub _address: u8,
}
impl Default for LZ4_streamHC_u {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[repr(align(8))]
#[derive(Copy, Clone)]
pub union AOCL_LZ4_streamHC_u {
    pub _address: u8,
}
impl Default for AOCL_LZ4_streamHC_u {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
extern "C" {
    pub fn LZ4_initStreamHC(
        buffer: *mut ::std::os::raw::c_void,
        size: usize,
    ) -> *mut LZ4_streamHC_t;
}
extern "C" {
    pub fn AOCL_LZ4_initStreamHC(
        buffer: *mut ::std::os::raw::c_void,
        size: usize,
    ) -> *mut AOCL_LZ4_streamHC_t;
}
pub const dictCtx_directive_noDictCtx: dictCtx_directive = 0;
pub const dictCtx_directive_usingDictCtxHc: dictCtx_directive = 1;
pub type dictCtx_directive = ::std::os::raw::c_int;
pub const HCfavor_e_favorCompressionRatio: HCfavor_e = 0;
pub const HCfavor_e_favorDecompressionSpeed: HCfavor_e = 1;
pub type HCfavor_e = ::std::os::raw::c_int;
extern "C" {
    pub fn LZ4_compressHC(
        source: *const ::std::os::raw::c_char,
        dest: *mut ::std::os::raw::c_char,
        inputSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_compressHC_limitedOutput(
        source: *const ::std::os::raw::c_char,
        dest: *mut ::std::os::raw::c_char,
        inputSize: ::std::os::raw::c_int,
        maxOutputSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_compressHC2(
        source: *const ::std::os::raw::c_char,
        dest: *mut ::std::os::raw::c_char,
        inputSize: ::std::os::raw::c_int,
        compressionLevel: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_compressHC2_limitedOutput(
        source: *const ::std::os::raw::c_char,
        dest: *mut ::std::os::raw::c_char,
        inputSize: ::std::os::raw::c_int,
        maxOutputSize: ::std::os::raw::c_int,
        compressionLevel: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_compressHC_withStateHC(
        state: *mut ::std::os::raw::c_void,
        source: *const ::std::os::raw::c_char,
        dest: *mut ::std::os::raw::c_char,
        inputSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_compressHC_limitedOutput_withStateHC(
        state: *mut ::std::os::raw::c_void,
        source: *const ::std::os::raw::c_char,
        dest: *mut ::std::os::raw::c_char,
        inputSize: ::std::os::raw::c_int,
        maxOutputSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_compressHC2_withStateHC(
        state: *mut ::std::os::raw::c_void,
        source: *const ::std::os::raw::c_char,
        dest: *mut ::std::os::raw::c_char,
        inputSize: ::std::os::raw::c_int,
        compressionLevel: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_compressHC2_limitedOutput_withStateHC(
        state: *mut ::std::os::raw::c_void,
        source: *const ::std::os::raw::c_char,
        dest: *mut ::std::os::raw::c_char,
        inputSize: ::std::os::raw::c_int,
        maxOutputSize: ::std::os::raw::c_int,
        compressionLevel: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_compressHC_continue(
        LZ4_streamHCPtr: *mut LZ4_streamHC_t,
        source: *const ::std::os::raw::c_char,
        dest: *mut ::std::os::raw::c_char,
        inputSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_compressHC_limitedOutput_continue(
        LZ4_streamHCPtr: *mut LZ4_streamHC_t,
        source: *const ::std::os::raw::c_char,
        dest: *mut ::std::os::raw::c_char,
        inputSize: ::std::os::raw::c_int,
        maxOutputSize: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_createHC(inputBuffer: *const ::std::os::raw::c_char) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn LZ4_freeHC(LZ4HC_Data: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_slideInputBufferHC(
        LZ4HC_Data: *mut ::std::os::raw::c_void,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn LZ4_compressHC2_continue(
        LZ4HC_Data: *mut ::std::os::raw::c_void,
        source: *const ::std::os::raw::c_char,
        dest: *mut ::std::os::raw::c_char,
        inputSize: ::std::os::raw::c_int,
        compressionLevel: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_compressHC2_limitedOutput_continue(
        LZ4HC_Data: *mut ::std::os::raw::c_void,
        source: *const ::std::os::raw::c_char,
        dest: *mut ::std::os::raw::c_char,
        inputSize: ::std::os::raw::c_int,
        maxOutputSize: ::std::os::raw::c_int,
        compressionLevel: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_sizeofStreamStateHC() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_resetStreamStateHC(
        state: *mut ::std::os::raw::c_void,
        inputBuffer: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4_resetStreamHC(
        streamHCPtr: *mut LZ4_streamHC_t,
        compressionLevel: ::std::os::raw::c_int,
    );
}
pub type LZ4F_errorCode_t = usize;
extern "C" {
    pub fn LZ4F_isError(code: LZ4F_errorCode_t) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn LZ4F_getErrorName(code: LZ4F_errorCode_t) -> *const ::std::os::raw::c_char;
}
pub const LZ4F_blockSizeID_t_LZ4F_default: LZ4F_blockSizeID_t = 0;
pub const LZ4F_blockSizeID_t_LZ4F_max64KB: LZ4F_blockSizeID_t = 4;
pub const LZ4F_blockSizeID_t_LZ4F_max256KB: LZ4F_blockSizeID_t = 5;
pub const LZ4F_blockSizeID_t_LZ4F_max1MB: LZ4F_blockSizeID_t = 6;
pub const LZ4F_blockSizeID_t_LZ4F_max4MB: LZ4F_blockSizeID_t = 7;
pub type LZ4F_blockSizeID_t = ::std::os::raw::c_int;
pub const LZ4F_blockMode_t_LZ4F_blockLinked: LZ4F_blockMode_t = 0;
pub const LZ4F_blockMode_t_LZ4F_blockIndependent: LZ4F_blockMode_t = 1;
pub type LZ4F_blockMode_t = ::std::os::raw::c_int;
pub const LZ4F_contentChecksum_t_LZ4F_noContentChecksum: LZ4F_contentChecksum_t = 0;
pub const LZ4F_contentChecksum_t_LZ4F_contentChecksumEnabled: LZ4F_contentChecksum_t = 1;
pub type LZ4F_contentChecksum_t = ::std::os::raw::c_int;
pub const LZ4F_blockChecksum_t_LZ4F_noBlockChecksum: LZ4F_blockChecksum_t = 0;
pub const LZ4F_blockChecksum_t_LZ4F_blockChecksumEnabled: LZ4F_blockChecksum_t = 1;
pub type LZ4F_blockChecksum_t = ::std::os::raw::c_int;
pub const LZ4F_frameType_t_LZ4F_frame: LZ4F_frameType_t = 0;
pub const LZ4F_frameType_t_LZ4F_skippableFrame: LZ4F_frameType_t = 1;
pub type LZ4F_frameType_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LZ4F_frameInfo_t {
    pub blockSizeID: LZ4F_blockSizeID_t,
    pub blockMode: LZ4F_blockMode_t,
    pub contentChecksumFlag: LZ4F_contentChecksum_t,
    pub frameType: LZ4F_frameType_t,
    pub contentSize: ::std::os::raw::c_ulonglong,
    pub dictID: ::std::os::raw::c_uint,
    pub blockChecksumFlag: LZ4F_blockChecksum_t,
}
impl Default for LZ4F_frameInfo_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LZ4F_preferences_t {
    pub frameInfo: LZ4F_frameInfo_t,
    pub compressionLevel: ::std::os::raw::c_int,
    pub autoFlush: ::std::os::raw::c_uint,
    pub favorDecSpeed: ::std::os::raw::c_uint,
    pub reserved: [::std::os::raw::c_uint; 3usize],
}
impl Default for LZ4F_preferences_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
extern "C" {
    pub fn LZ4F_compressionLevel_max() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn LZ4F_compressFrameBound(
        srcSize: usize,
        preferencesPtr: *const LZ4F_preferences_t,
    ) -> usize;
}
extern "C" {
    pub fn LZ4F_compressFrame(
        dstBuffer: *mut ::std::os::raw::c_void,
        dstCapacity: usize,
        srcBuffer: *const ::std::os::raw::c_void,
        srcSize: usize,
        preferencesPtr: *const LZ4F_preferences_t,
    ) -> usize;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LZ4F_cctx_s {
    _unused: [u8; 0],
}
pub type LZ4F_cctx = LZ4F_cctx_s;
pub type LZ4F_compressionContext_t = *mut LZ4F_cctx;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct LZ4F_compressOptions_t {
    pub stableSrc: ::std::os::raw::c_uint,
    pub reserved: [::std::os::raw::c_uint; 3usize],
}
extern "C" {
    pub fn LZ4F_getVersion() -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn LZ4F_createCompressionContext(
        cctxPtr: *mut *mut LZ4F_cctx,
        version: ::std::os::raw::c_uint,
    ) -> LZ4F_errorCode_t;
}
extern "C" {
    pub fn LZ4F_freeCompressionContext(cctx: *mut LZ4F_cctx) -> LZ4F_errorCode_t;
}
extern "C" {
    pub fn LZ4F_compressBegin(
        cctx: *mut LZ4F_cctx,
        dstBuffer: *mut ::std::os::raw::c_void,
        dstCapacity: usize,
        prefsPtr: *const LZ4F_preferences_t,
    ) -> usize;
}
extern "C" {
    pub fn LZ4F_compressBound(srcSize: usize, prefsPtr: *const LZ4F_preferences_t) -> usize;
}
extern "C" {
    pub fn LZ4F_compressUpdate(
        cctx: *mut LZ4F_cctx,
        dstBuffer: *mut ::std::os::raw::c_void,
        dstCapacity: usize,
        srcBuffer: *const ::std::os::raw::c_void,
        srcSize: usize,
        cOptPtr: *const LZ4F_compressOptions_t,
    ) -> usize;
}
extern "C" {
    pub fn LZ4F_flush(
        cctx: *mut LZ4F_cctx,
        dstBuffer: *mut ::std::os::raw::c_void,
        dstCapacity: usize,
        cOptPtr: *const LZ4F_compressOptions_t,
    ) -> usize;
}
extern "C" {
    pub fn LZ4F_compressEnd(
        cctx: *mut LZ4F_cctx,
        dstBuffer: *mut ::std::os::raw::c_void,
        dstCapacity: usize,
        cOptPtr: *const LZ4F_compressOptions_t,
    ) -> usize;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LZ4F_dctx_s {
    _unused: [u8; 0],
}
pub type LZ4F_dctx = LZ4F_dctx_s;
pub type LZ4F_decompressionContext_t = *mut LZ4F_dctx;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct LZ4F_decompressOptions_t {
    pub stableDst: ::std::os::raw::c_uint,
    pub skipChecksums: ::std::os::raw::c_uint,
    pub reserved1: ::std::os::raw::c_uint,
    pub reserved0: ::std::os::raw::c_uint,
}
extern "C" {
    pub fn LZ4F_createDecompressionContext(
        dctxPtr: *mut *mut LZ4F_dctx,
        version: ::std::os::raw::c_uint,
    ) -> LZ4F_errorCode_t;
}
extern "C" {
    pub fn LZ4F_freeDecompressionContext(dctx: *mut LZ4F_dctx) -> LZ4F_errorCode_t;
}
extern "C" {
    pub fn LZ4F_headerSize(src: *const ::std::os::raw::c_void, srcSize: usize) -> usize;
}
extern "C" {
    pub fn LZ4F_getFrameInfo(
        dctx: *mut LZ4F_dctx,
        frameInfoPtr: *mut LZ4F_frameInfo_t,
        srcBuffer: *const ::std::os::raw::c_void,
        srcSizePtr: *mut usize,
    ) -> usize;
}
extern "C" {
    pub fn LZ4F_decompress(
        dctx: *mut LZ4F_dctx,
        dstBuffer: *mut ::std::os::raw::c_void,
        dstSizePtr: *mut usize,
        srcBuffer: *const ::std::os::raw::c_void,
        srcSizePtr: *mut usize,
        dOptPtr: *const LZ4F_decompressOptions_t,
    ) -> usize;
}
extern "C" {
    pub fn LZ4F_resetDecompressionContext(dctx: *mut LZ4F_dctx);
}
pub const snappy_status_SNAPPY_OK: snappy_status = 0;
pub const snappy_status_SNAPPY_INVALID_INPUT: snappy_status = 1;
pub const snappy_status_SNAPPY_BUFFER_TOO_SMALL: snappy_status = 2;
pub type snappy_status = ::std::os::raw::c_int;
extern "C" {
    pub fn snappy_compress(
        input: *const ::std::os::raw::c_char,
        input_length: usize,
        compressed: *mut ::std::os::raw::c_char,
        compressed_length: *mut usize,
    ) -> snappy_status;
}
extern "C" {
    pub fn snappy_uncompress(
        compressed: *const ::std::os::raw::c_char,
        compressed_length: usize,
        uncompressed: *mut ::std::os::raw::c_char,
        uncompressed_length: *mut usize,
    ) -> snappy_status;
}
extern "C" {
    pub fn snappy_max_compressed_length(source_length: usize) -> usize;
}
extern "C" {
    pub fn snappy_uncompressed_length(
        compressed: *const ::std::os::raw::c_char,
        compressed_length: usize,
        result: *mut usize,
    ) -> snappy_status;
}
extern "C" {
    pub fn snappy_validate_compressed_buffer(
        compressed: *const ::std::os::raw::c_char,
        compressed_length: usize,
    ) -> snappy_status;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct bz_stream {
    pub next_in: *mut ::std::os::raw::c_char,
    pub avail_in: ::std::os::raw::c_uint,
    pub total_in_lo32: ::std::os::raw::c_uint,
    pub total_in_hi32: ::std::os::raw::c_uint,
    pub next_out: *mut ::std::os::raw::c_char,
    pub avail_out: ::std::os::raw::c_uint,
    pub total_out_lo32: ::std::os::raw::c_uint,
    pub total_out_hi32: ::std::os::raw::c_uint,
    pub state: *mut ::std::os::raw::c_void,
    pub bzalloc: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut ::std::os::raw::c_void,
            arg2: ::std::os::raw::c_int,
            arg3: ::std::os::raw::c_int,
        ) -> *mut ::std::os::raw::c_void,
    >,
    pub bzfree: ::std::option::Option<
        unsafe extern "C" fn(arg1: *mut ::std::os::raw::c_void, arg2: *mut ::std::os::raw::c_void),
    >,
    pub opaque: *mut ::std::os::raw::c_void,
}
impl Default for bz_stream {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _iobuf {
    pub _Placeholder: *mut ::std::os::raw::c_void,
}
impl Default for _iobuf {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type FILE = _iobuf;
extern "C" {
    pub fn BZ2_bzCompressInit(
        strm: *mut bz_stream,
        blockSize100k: ::std::os::raw::c_int,
        verbosity: ::std::os::raw::c_int,
        workFactor: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn BZ2_bzCompress(
        strm: *mut bz_stream,
        action: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn BZ2_bzCompressEnd(strm: *mut bz_stream) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn BZ2_bzDecompressInit(
        strm: *mut bz_stream,
        verbosity: ::std::os::raw::c_int,
        small: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn BZ2_bzDecompress(strm: *mut bz_stream) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn BZ2_bzDecompressEnd(strm: *mut bz_stream) -> ::std::os::raw::c_int;
}
pub type BZFILE = ::std::os::raw::c_void;
extern "C" {
    pub fn BZ2_bzReadOpen(
        bzerror: *mut ::std::os::raw::c_int,
        f: *mut FILE,
        verbosity: ::std::os::raw::c_int,
        small: ::std::os::raw::c_int,
        unused: *mut ::std::os::raw::c_void,
        nUnused: ::std::os::raw::c_int,
    ) -> *mut BZFILE;
}
extern "C" {
    pub fn BZ2_bzReadClose(bzerror: *mut ::std::os::raw::c_int, b: *mut BZFILE);
}
extern "C" {
    pub fn BZ2_bzReadGetUnused(
        bzerror: *mut ::std::os::raw::c_int,
        b: *mut BZFILE,
        unused: *mut *mut ::std::os::raw::c_void,
        nUnused: *mut ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn BZ2_bzRead(
        bzerror: *mut ::std::os::raw::c_int,
        b: *mut BZFILE,
        buf: *mut ::std::os::raw::c_void,
        len: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn BZ2_bzWriteOpen(
        bzerror: *mut ::std::os::raw::c_int,
        f: *mut FILE,
        blockSize100k: ::std::os::raw::c_int,
        verbosity: ::std::os::raw::c_int,
        workFactor: ::std::os::raw::c_int,
    ) -> *mut BZFILE;
}
extern "C" {
    pub fn BZ2_bzWrite(
        bzerror: *mut ::std::os::raw::c_int,
        b: *mut BZFILE,
        buf: *mut ::std::os::raw::c_void,
        len: ::std::os::raw::c_int,
    );
}
extern "C" {
    pub fn BZ2_bzWriteClose(
        bzerror: *mut ::std::os::raw::c_int,
        b: *mut BZFILE,
        abandon: ::std::os::raw::c_int,
        nbytes_in: *mut ::std::os::raw::c_uint,
        nbytes_out: *mut ::std::os::raw::c_uint,
    );
}
extern "C" {
    pub fn BZ2_bzWriteClose64(
        bzerror: *mut ::std::os::raw::c_int,
        b: *mut BZFILE,
        abandon: ::std::os::raw::c_int,
        nbytes_in_lo32: *mut ::std::os::raw::c_uint,
        nbytes_in_hi32: *mut ::std::os::raw::c_uint,
        nbytes_out_lo32: *mut ::std::os::raw::c_uint,
        nbytes_out_hi32: *mut ::std::os::raw::c_uint,
    );
}
extern "C" {
    pub fn BZ2_bzCompressBound(insize: ::std::os::raw::c_uint) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn BZ2_bzBuffToBuffCompress(
        dest: *mut ::std::os::raw::c_char,
        destLen: *mut ::std::os::raw::c_uint,
        source: *mut ::std::os::raw::c_char,
        sourceLen: ::std::os::raw::c_uint,
        blockSize100k: ::std::os::raw::c_int,
        verbosity: ::std::os::raw::c_int,
        workFactor: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn BZ2_bzBuffToBuffDecompress(
        dest: *mut ::std::os::raw::c_char,
        destLen: *mut ::std::os::raw::c_uint,
        source: *mut ::std::os::raw::c_char,
        sourceLen: ::std::os::raw::c_uint,
        small: ::std::os::raw::c_int,
        verbosity: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn BZ2_bzlibVersion() -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn BZ2_bzopen(
        path: *const ::std::os::raw::c_char,
        mode: *const ::std::os::raw::c_char,
    ) -> *mut BZFILE;
}
extern "C" {
    pub fn BZ2_bzdopen(
        fd: ::std::os::raw::c_int,
        mode: *const ::std::os::raw::c_char,
    ) -> *mut BZFILE;
}
extern "C" {
    pub fn BZ2_bzread(
        b: *mut BZFILE,
        buf: *mut ::std::os::raw::c_void,
        len: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn BZ2_bzwrite(
        b: *mut BZFILE,
        buf: *mut ::std::os::raw::c_void,
        len: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn BZ2_bzflush(b: *mut BZFILE) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn BZ2_bzclose(b: *mut BZFILE);
}
extern "C" {
    pub fn BZ2_bzerror(
        b: *mut BZFILE,
        errnum: *mut ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn aocl_setup_bzip2(
        optOff: ::std::os::raw::c_int,
        optLevel: ::std::os::raw::c_int,
        insize: usize,
        level: usize,
        windowLog: usize,
    ) -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn aocl_destroy_bzip2();
}
pub type SRes = ::std::os::raw::c_int;
pub type WRes = ::std::os::raw::c_uint;
pub type Byte = ::std::os::raw::c_uchar;
pub type Int16 = ::std::os::raw::c_short;
pub type UInt16 = ::std::os::raw::c_ushort;
pub type Int32 = ::std::os::raw::c_int;
pub type UInt32 = ::std::os::raw::c_uint;
pub type Int64 = ::std::os::raw::c_longlong;
pub type UInt64 = ::std::os::raw::c_ulonglong;
pub type SizeT = usize;
pub type BoolInt = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct IByteIn {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct IByteOut {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct ISeqInStream {
    pub _address: u8,
}
extern "C" {
    pub fn SeqInStream_Read(
        stream: *const ISeqInStream,
        buf: *mut ::std::os::raw::c_void,
        size: usize,
    ) -> SRes;
}
extern "C" {
    pub fn SeqInStream_Read2(
        stream: *const ISeqInStream,
        buf: *mut ::std::os::raw::c_void,
        size: usize,
        errorType: SRes,
    ) -> SRes;
}
extern "C" {
    pub fn SeqInStream_ReadByte(stream: *const ISeqInStream, buf: *mut Byte) -> SRes;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct ISeqOutStream {
    pub _address: u8,
}
pub const ESzSeek_SZ_SEEK_SET: ESzSeek = 0;
pub const ESzSeek_SZ_SEEK_CUR: ESzSeek = 1;
pub const ESzSeek_SZ_SEEK_END: ESzSeek = 2;
pub type ESzSeek = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct ISeekInStream {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct ILookInStream {
    pub _address: u8,
}
extern "C" {
    pub fn LookInStream_LookRead(
        stream: *const ILookInStream,
        buf: *mut ::std::os::raw::c_void,
        size: *mut usize,
    ) -> SRes;
}
extern "C" {
    pub fn LookInStream_SeekTo(stream: *const ILookInStream, offset: UInt64) -> SRes;
}
extern "C" {
    pub fn LookInStream_Read2(
        stream: *const ILookInStream,
        buf: *mut ::std::os::raw::c_void,
        size: usize,
        errorType: SRes,
    ) -> SRes;
}
extern "C" {
    pub fn LookInStream_Read(
        stream: *const ILookInStream,
        buf: *mut ::std::os::raw::c_void,
        size: usize,
    ) -> SRes;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CLookToRead2 {
    pub vt: ILookInStream,
    pub realStream: *const ISeekInStream,
    pub pos: usize,
    pub size: usize,
    pub buf: *mut Byte,
    pub bufSize: usize,
}
impl Default for CLookToRead2 {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
extern "C" {
    pub fn LookToRead2_CreateVTable(p: *mut CLookToRead2, lookahead: ::std::os::raw::c_int);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CSecToLook {
    pub vt: ISeqInStream,
    pub realStream: *const ILookInStream,
}
impl Default for CSecToLook {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
extern "C" {
    pub fn SecToLook_CreateVTable(p: *mut CSecToLook);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CSecToRead {
    pub vt: ISeqInStream,
    pub realStream: *const ILookInStream,
}
impl Default for CSecToRead {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
extern "C" {
    pub fn SecToRead_CreateVTable(p: *mut CSecToRead);
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct ICompressProgress {
    pub _address: u8,
}
pub type ISzAllocPtr = *const ISzAlloc;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct ISzAlloc {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _CLzmaEncProps {
    pub level: ::std::os::raw::c_int,
    pub dictSize: UInt32,
    pub lc: ::std::os::raw::c_int,
    pub lp: ::std::os::raw::c_int,
    pub pb: ::std::os::raw::c_int,
    pub algo: ::std::os::raw::c_int,
    pub fb: ::std::os::raw::c_int,
    pub btMode: ::std::os::raw::c_int,
    pub numHashBytes: ::std::os::raw::c_int,
    pub mc: UInt32,
    pub writeEndMark: ::std::os::raw::c_uint,
    pub numThreads: ::std::os::raw::c_int,
    pub reduceSize: UInt64,
    pub affinity: UInt64,
    pub srcLen: usize,
    pub cacheEfficientStrategy: ::std::os::raw::c_int,
}
pub type CLzmaEncProps = _CLzmaEncProps;
extern "C" {
    pub fn LzmaEncProps_Init(p: *mut CLzmaEncProps);
}
extern "C" {
    pub fn LzmaEncProps_Normalize(p: *mut CLzmaEncProps);
}
extern "C" {
    pub fn LzmaEncProps_GetDictSize(props2: *const CLzmaEncProps) -> UInt32;
}
pub type CLzmaEncHandle = *mut ::std::os::raw::c_void;
extern "C" {
    pub fn LzmaEnc_Create(alloc: ISzAllocPtr) -> CLzmaEncHandle;
}
extern "C" {
    pub fn LzmaEnc_Destroy(p: CLzmaEncHandle, alloc: ISzAllocPtr, allocBig: ISzAllocPtr);
}
extern "C" {
    pub fn LzmaEnc_SetProps(p: CLzmaEncHandle, props: *const CLzmaEncProps) -> SRes;
}
extern "C" {
    pub fn LzmaEnc_SetDataSize(p: CLzmaEncHandle, expectedDataSiize: UInt64);
}
extern "C" {
    pub fn LzmaEnc_WriteProperties(
        p: CLzmaEncHandle,
        properties: *mut Byte,
        size: *mut SizeT,
    ) -> SRes;
}
extern "C" {
    pub fn LzmaEnc_IsWriteEndMark(p: CLzmaEncHandle) -> ::std::os::raw::c_uint;
}
extern "C" {
    pub fn LzmaEnc_Encode(
        p: CLzmaEncHandle,
        outStream: *mut ISeqOutStream,
        inStream: *mut ISeqInStream,
        progress: *mut ICompressProgress,
        alloc: ISzAllocPtr,
        allocBig: ISzAllocPtr,
    ) -> SRes;
}
extern "C" {
    pub fn LzmaEnc_MemEncode(
        p: CLzmaEncHandle,
        dest: *mut Byte,
        destLen: *mut SizeT,
        src: *const Byte,
        srcLen: SizeT,
        writeEndMark: ::std::os::raw::c_int,
        progress: *mut ICompressProgress,
        alloc: ISzAllocPtr,
        allocBig: ISzAllocPtr,
    ) -> SRes;
}
extern "C" {
    pub fn Lzma_compressBound(insize: usize) -> usize;
}
extern "C" {
    pub fn LzmaEncode(
        dest: *mut Byte,
        destLen: *mut SizeT,
        src: *const Byte,
        srcLen: SizeT,
        props: *const CLzmaEncProps,
        propsEncoded: *mut Byte,
        propsSize: *mut SizeT,
        writeEndMark: ::std::os::raw::c_int,
        progress: *mut ICompressProgress,
        alloc: ISzAllocPtr,
        allocBig: ISzAllocPtr,
    ) -> SRes;
}
extern "C" {
    pub fn aocl_setup_lzma_encode(
        optOff: ::std::os::raw::c_int,
        optLevel: ::std::os::raw::c_int,
        insize: usize,
        level: usize,
        windowLog: usize,
    );
}
extern "C" {
    pub fn aocl_destroy_lzma_encode();
}
extern "C" {
    pub fn AOCL_LzmaEncProps_Normalize(p: *mut CLzmaEncProps);
}
extern "C" {
    pub fn AOCL_LzmaEnc_SetProps(pp: CLzmaEncHandle, props2: *const CLzmaEncProps) -> SRes;
}
pub type CLzmaProb = UInt16;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _CLzmaProps {
    pub lc: Byte,
    pub lp: Byte,
    pub pb: Byte,
    pub _pad_: Byte,
    pub dicSize: UInt32,
}
pub type CLzmaProps = _CLzmaProps;
extern "C" {
    pub fn LzmaProps_Decode(
        p: *mut CLzmaProps,
        data: *const Byte,
        size: ::std::os::raw::c_uint,
    ) -> SRes;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CLzmaDec {
    pub prop: CLzmaProps,
    pub probs: *mut CLzmaProb,
    pub probs_1664: *mut CLzmaProb,
    pub dic: *mut Byte,
    pub dicBufSize: SizeT,
    pub dicPos: SizeT,
    pub buf: *const Byte,
    pub range: UInt32,
    pub code: UInt32,
    pub processedPos: UInt32,
    pub checkDicSize: UInt32,
    pub reps: [UInt32; 4usize],
    pub state: UInt32,
    pub remainLen: UInt32,
    pub numProbs: UInt32,
    pub tempBufSize: ::std::os::raw::c_uint,
    pub tempBuf: [Byte; 20usize],
}
impl Default for CLzmaDec {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
extern "C" {
    pub fn LzmaDec_Init(p: *mut CLzmaDec);
}
pub const ELzmaFinishMode_LZMA_FINISH_ANY: ELzmaFinishMode = 0;
pub const ELzmaFinishMode_LZMA_FINISH_END: ELzmaFinishMode = 1;
pub type ELzmaFinishMode = ::std::os::raw::c_int;
pub const ELzmaStatus_LZMA_STATUS_NOT_SPECIFIED: ELzmaStatus = 0;
pub const ELzmaStatus_LZMA_STATUS_FINISHED_WITH_MARK: ELzmaStatus = 1;
pub const ELzmaStatus_LZMA_STATUS_NOT_FINISHED: ELzmaStatus = 2;
pub const ELzmaStatus_LZMA_STATUS_NEEDS_MORE_INPUT: ELzmaStatus = 3;
pub const ELzmaStatus_LZMA_STATUS_MAYBE_FINISHED_WITHOUT_MARK: ELzmaStatus = 4;
pub type ELzmaStatus = ::std::os::raw::c_int;
extern "C" {
    pub fn LzmaDec_AllocateProbs(
        p: *mut CLzmaDec,
        props: *const Byte,
        propsSize: ::std::os::raw::c_uint,
        alloc: ISzAllocPtr,
    ) -> SRes;
}
extern "C" {
    pub fn LzmaDec_FreeProbs(p: *mut CLzmaDec, alloc: ISzAllocPtr);
}
extern "C" {
    pub fn LzmaDec_Allocate(
        p: *mut CLzmaDec,
        props: *const Byte,
        propsSize: ::std::os::raw::c_uint,
        alloc: ISzAllocPtr,
    ) -> SRes;
}
extern "C" {
    pub fn LzmaDec_Free(p: *mut CLzmaDec, alloc: ISzAllocPtr);
}
extern "C" {
    pub fn LzmaDec_DecodeToDic(
        p: *mut CLzmaDec,
        dicLimit: SizeT,
        src: *const Byte,
        srcLen: *mut SizeT,
        finishMode: ELzmaFinishMode,
        status: *mut ELzmaStatus,
    ) -> SRes;
}
extern "C" {
    pub fn LzmaDec_DecodeToBuf(
        p: *mut CLzmaDec,
        dest: *mut Byte,
        destLen: *mut SizeT,
        src: *const Byte,
        srcLen: *mut SizeT,
        finishMode: ELzmaFinishMode,
        status: *mut ELzmaStatus,
    ) -> SRes;
}
extern "C" {
    pub fn LzmaDecode(
        dest: *mut Byte,
        destLen: *mut SizeT,
        src: *const Byte,
        srcLen: *mut SizeT,
        propData: *const Byte,
        propSize: ::std::os::raw::c_uint,
        finishMode: ELzmaFinishMode,
        status: *mut ELzmaStatus,
        alloc: ISzAllocPtr,
    ) -> SRes;
}
extern "C" {
    pub fn aocl_setup_lzma_decode(
        optOff: ::std::os::raw::c_int,
        optLevel: ::std::os::raw::c_int,
        insize: usize,
        level: usize,
        windowLog: usize,
    );
}
extern "C" {
    pub fn aocl_destroy_lzma_decode();
}
