/* automatically generated by rust-bindgen 0.69.5 */

pub const ALC_E_FLAG_SSSE3: u32 = 1;
pub const ALC_E_FLAG_AES: u32 = 24;
pub const ALC_E_FLAG_AVX: u32 = 26;
pub const ALC_E_FLAG_RDRAND: u32 = 29;
pub const ALC_E_FLAG_TSC_ADJUST: u32 = 63;
pub const ALC_E_FLAG_AVX2: u32 = 66;
pub const ALC_E_FLAG_BMI2: u32 = 68;
pub const ALC_E_FLAG_TSX: u32 = 71;
pub const ALC_E_FLAG_AVX512F: u32 = 73;
pub const ALC_E_FLAG_AVX512DQ: u32 = 74;
pub const ALC_E_FLAG_RDSEED: u32 = 75;
pub const ALC_E_FLAG_ADX: u32 = 76;
pub const ALC_E_FLAG_AVX512_IFMA: u32 = 78;
pub const ALC_E_FLAG_AVX512PF: u32 = 82;
pub const ALC_E_FLAG_AVX512ER: u32 = 83;
pub const ALC_E_FLAG_AVX512CD: u32 = 84;
pub const ALC_E_FLAG_SHA: u32 = 85;
pub const ALC_E_FLAG_SHA_NI: u32 = 85;
pub const ALC_E_FLAG_AVX512BW: u32 = 86;
pub const ALC_E_FLAG_AVX512VL: u32 = 87;
pub const ALC_E_FLAG_AVX512_VBMI: u32 = 88;
pub const ALC_E_FLAG_AVX512_VPOPCNTDQ: u32 = 92;
pub const ALC_E_FLAG_AVXVNNI: u32 = 98;
pub const ALC_E_FLAG_VAES: u32 = 155;
pub const ALC_E_FLAG_VPCLMULQDQ: u32 = 156;
pub const ALC_E_FLAG_AVX512_VNNI: u32 = 157;
pub const ALC_E_FLAG_AVX512_BITALG: u32 = 158;
pub const ALC_E_FLAG_AVX512_VBMI2: u32 = 159;
pub const ALC_E_FLAG_MOVDIRI: u32 = 160;
pub const ALC_E_FLAG_MOVDIR64B: u32 = 161;
pub const ALC_E_FLAG_AVX512VPINTERSECT: u32 = 162;
pub const ALC_E_FLAG_X2AVIC: u32 = 163;
pub const ALC_CPUID_FLAG_MAX: u32 = 164;
pub const _AU_CONFIG_H_INCLUDED: u32 = 2;
pub const AU_BUILD_TYPE_RELEASE: u32 = 1;
pub const AU_BUILD_TYPE_DEBUG: u32 = 0;
pub const AU_BUILD_TYPE_DEVELOPER: u32 = 0;
pub const AU_CPU_ARCH_X86: u32 = 1;
pub const AU_COMPILER_IS_CLANG: u32 = 1;
pub type Int8 = i8;
pub type Int16 = i16;
pub type Int32 = i32;
pub type Int64 = i64;
pub type Uint8 = u8;
pub type Uint16 = u16;
pub type Uint32 = u32;
pub type Uint64 = u64;
pub type pVoid = *mut ::std::os::raw::c_void;
pub type pInt8 = *mut i8;
pub type pInt16 = *mut i16;
pub type pInt32 = *mut i32;
pub type pInt64 = *mut i64;
pub type pUint8 = *mut u8;
pub type pUint16 = *mut u16;
pub type pUint32 = *mut u32;
pub type pUint64 = *mut u64;
pub type au_handle_t = *mut ::std::os::raw::c_void;
pub type au_cpu_num_t = Uint32;
pub type au_error_t = Uint64;
pub type au_cpu_flag_t = Uint32;
extern "C" {
    pub fn au_cpuid_is_amd(cpu_num: au_cpu_num_t) -> bool;
}
extern "C" {
    pub fn au_cpuid_get_vendor(
        cpu_num: au_cpu_num_t,
        vend_info: *mut ::std::os::raw::c_char,
        size: usize,
    );
}
extern "C" {
    pub fn au_cpuid_arch_is_zen(cpu_num: au_cpu_num_t) -> bool;
}
extern "C" {
    pub fn au_cpuid_arch_is_zenplus(cpu_num: au_cpu_num_t) -> bool;
}
extern "C" {
    pub fn au_cpuid_arch_is_zen2(cpu_num: au_cpu_num_t) -> bool;
}
extern "C" {
    pub fn au_cpuid_arch_is_zen3(cpu_num: au_cpu_num_t) -> bool;
}
extern "C" {
    pub fn au_cpuid_arch_is_zen4(cpu_num: au_cpu_num_t) -> bool;
}
extern "C" {
    pub fn au_cpuid_arch_is_zen5(cpu_num: au_cpu_num_t) -> bool;
}
extern "C" {
    pub fn au_cpuid_arch_is_x86_64v2(cpu_num: au_cpu_num_t) -> bool;
}
extern "C" {
    pub fn au_cpuid_arch_is_x86_64v3(cpu_num: au_cpu_num_t) -> bool;
}
extern "C" {
    pub fn au_cpuid_arch_is_x86_64v4(cpu_num: au_cpu_num_t) -> bool;
}
extern "C" {
    pub fn au_cpuid_arch_is_zen_family(cpu_num: au_cpu_num_t) -> bool;
}
extern "C" {
    pub fn au_cpuid_has_flag(
        cpu_num: au_cpu_num_t,
        flag_array: *const *const ::std::os::raw::c_char,
        count: ::std::os::raw::c_int,
    ) -> *mut bool;
}
extern "C" {
    pub fn au_cpuid_has_flags_all(
        cpu_num: au_cpu_num_t,
        flag_array: *const *const ::std::os::raw::c_char,
        count: ::std::os::raw::c_int,
    ) -> bool;
}
extern "C" {
    pub fn au_cpuid_has_flags_any(
        cpu_num: au_cpu_num_t,
        flag_array: *const *const ::std::os::raw::c_char,
        count: ::std::os::raw::c_int,
    ) -> bool;
}
extern "C" {
    pub fn au_cpuid_has_flags(
        cpu_num: au_cpu_num_t,
        flag_array: *const *const ::std::os::raw::c_char,
        count: ::std::os::raw::c_int,
    ) -> bool;
}
extern "C" {
    pub fn au_cpuid_is_error(err: au_error_t) -> bool;
}
extern "C" {
    pub fn alci_is_amd(cpu_num: au_cpu_num_t) -> bool;
}
extern "C" {
    pub fn alci_cpu_get_vendor(
        cpu_num: au_cpu_num_t,
        arr: *mut ::std::os::raw::c_char,
        size: usize,
    ) -> au_error_t;
}
extern "C" {
    pub fn alci_arch_is_zen(cpu_num: au_cpu_num_t) -> bool;
}
extern "C" {
    pub fn alci_arch_is_zen2(cpu_num: au_cpu_num_t) -> bool;
}
extern "C" {
    pub fn alci_arch_is_zen3(cpu_num: au_cpu_num_t) -> bool;
}
extern "C" {
    pub fn alci_arch_is_zen4(cpu_num: au_cpu_num_t) -> bool;
}
extern "C" {
    pub fn alci_arch_is_zen5(cpu_num: au_cpu_num_t) -> bool;
}
extern "C" {
    pub fn alci_cpu_has_flag(cpu_num: au_cpu_num_t, flag: au_cpu_flag_t) -> bool;
}
pub const __au_error_code_eError_Ok: __au_error_code = 0;
pub const __au_error_code_eError_None: __au_error_code = 0;
pub const __au_error_code_eError_Generic: __au_error_code = 1;
pub const __au_error_code_eError_NotSupported: __au_error_code = 2;
pub const __au_error_code_eError_InvalidArgument: __au_error_code = 3;
pub const __au_error_code_eError_BadPointer: __au_error_code = 4;
pub const __au_error_code_eError_NoMemory: __au_error_code = 5;
pub const __au_error_code_eError_InvalidSize: __au_error_code = 6;
pub type __au_error_code = ::std::os::raw::c_int;
pub use self::__au_error_code as au_error_code_t;
extern "C" {
    pub fn au_is_error(err: au_error_t) -> bool;
}
pub type HANDLE = *mut ::std::os::raw::c_void;
pub type pthread_t = HANDLE;
extern "C" {
    pub fn au_pin_threads_core(threadList: *mut pthread_t, threadListSize: usize);
}
extern "C" {
    pub fn au_pin_threads_logical(threadList: *mut pthread_t, threadListSize: usize);
}
extern "C" {
    pub fn au_pin_threads_spread(threadList: *mut pthread_t, threadListSize: usize);
}
extern "C" {
    pub fn au_pin_threads_custom(
        threadList: *mut pthread_t,
        threadListSize: usize,
        affinityVector: *mut ::std::os::raw::c_int,
        affinityVectorSize: usize,
    );
}
extern "C" {
    pub fn au_get_version_major() -> Uint32;
}
extern "C" {
    pub fn au_get_version_minor() -> Uint32;
}
extern "C" {
    pub fn au_get_version_patch() -> Uint32;
}
extern "C" {
    pub fn au_get_version_str() -> *const ::std::os::raw::c_char;
}
