/* automatically generated by rust-bindgen 0.69.5 */

pub const SECRNG_SUCCESS: u32 = 2;
pub const SECRNG_SUPPORTED: u32 = 1;
pub const SECRNG_NOT_SUPPORTED: i32 = -1;
pub const SECRNG_FAILURE: i32 = -2;
pub const SECRNG_INVALID_INPUT: i32 = -3;
extern "C" {
    pub fn is_RDRAND_supported() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn is_RDSEED_supported() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn get_rdrand16u(
        rng_val: *mut u16,
        retry_count: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn get_rdseed16u(
        rng_val: *mut u16,
        retry_count: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn get_rdrand32u(
        rng_val: *mut u32,
        retry_count: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn get_rdseed32u(
        rng_val: *mut u32,
        retry_count: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn get_rdrand64u(
        rng_val: *mut u64,
        retry_count: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn get_rdseed64u(
        rng_val: *mut u64,
        retry_count: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn get_rdrand32u_arr(
        rng_arr: *mut u32,
        N: ::std::os::raw::c_uint,
        retry_count: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn get_rdseed32u_arr(
        rng_arr: *mut u32,
        N: ::std::os::raw::c_uint,
        retry_count: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn get_rdrand64u_arr(
        rng_arr: *mut u64,
        N: ::std::os::raw::c_uint,
        retry_count: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn get_rdseed64u_arr(
        rng_arr: *mut u64,
        N: ::std::os::raw::c_uint,
        retry_count: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn get_rdrand_bytes_arr(
        rng_arr: *mut ::std::os::raw::c_uchar,
        N: ::std::os::raw::c_uint,
        retry_count: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn get_rdseed_bytes_arr(
        rng_arr: *mut ::std::os::raw::c_uchar,
        N: ::std::os::raw::c_uint,
        retry_count: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn get_secrngversion() -> *const ::std::os::raw::c_char;
}
