/* automatically generated by rust-bindgen 0.69.5 */

pub const DA_INT_FMT: &[u8; 2] = b"d\0";
pub const da_status__da_status_success: da_status_ = 0;
pub const da_status__da_status_internal_error: da_status_ = 1;
pub const da_status__da_status_memory_error: da_status_ = 2;
pub const da_status__da_status_invalid_pointer: da_status_ = 3;
pub const da_status__da_status_invalid_input: da_status_ = 4;
pub const da_status__da_status_not_implemented: da_status_ = 5;
pub const da_status__da_status_out_of_date: da_status_ = 6;
pub const da_status__da_status_wrong_type: da_status_ = 7;
pub const da_status__da_status_overflow: da_status_ = 8;
pub const da_status__da_status_invalid_handle_type: da_status_ = 9;
pub const da_status__da_status_handle_not_initialized: da_status_ = 10;
pub const da_status__da_status_store_not_initialized: da_status_ = 11;
pub const da_status__da_status_invalid_option: da_status_ = 12;
pub const da_status__da_status_incompatible_options: da_status_ = 13;
pub const da_status__da_status_operation_failed: da_status_ = 14;
pub const da_status__da_status_invalid_leading_dimension: da_status_ = 15;
pub const da_status__da_status_negative_data: da_status_ = 16;
pub const da_status__da_status_invalid_array_dimension: da_status_ = 17;
pub const da_status__da_status_unknown_query: da_status_ = 18;
pub const da_status__da_status_incorrect_output: da_status_ = 19;
pub const da_status__da_status_no_data: da_status_ = 20;
pub const da_status__da_status_maxit: da_status_ = 21;
pub const da_status__da_status_maxtime: da_status_ = 22;
pub const da_status__da_status_numerical_difficulties: da_status_ = 23;
pub const da_status__da_status_bad_derivatives: da_status_ = 24;
pub const da_status__da_status_arch_not_supported: da_status_ = 25;
pub const da_status__da_status_file_reading_error: da_status_ = 100;
pub const da_status__da_status_parsing_error: da_status_ = 101;
pub const da_status__da_status_missing_data: da_status_ = 102;
pub const da_status__da_status_option_not_found: da_status_ = 400;
pub const da_status__da_status_option_locked: da_status_ = 401;
pub const da_status__da_status_option_wrong_type: da_status_ = 402;
pub const da_status__da_status_option_invalid_bounds: da_status_ = 403;
pub const da_status__da_status_option_invalid_value: da_status_ = 404;
pub const da_status__da_status_optimization_usrstop: da_status_ = 500;
pub const da_status__da_status_optimization_infeasible: da_status_ = 501;
pub const da_status__da_status_optimization_empty_space: da_status_ = 502;
pub const da_status__da_status_missing_block: da_status_ = 600;
pub const da_status__da_status_full_extraction: da_status_ = 601;
pub type da_status_ = ::std::os::raw::c_int;
pub use self::da_status_ as da_status;
pub const da_severity__DA_NOTSET: da_severity_ = 0;
pub const da_severity__DA_WARNING: da_severity_ = 1;
pub const da_severity__DA_ERROR: da_severity_ = 2;
pub type da_severity_ = ::std::os::raw::c_int;
pub use self::da_severity_ as da_severity;
pub const da_precision__da_unknown: da_precision_ = 255;
pub const da_precision__da_double: da_precision_ = 0;
pub const da_precision__da_single: da_precision_ = 1;
pub type da_precision_ = ::std::os::raw::c_int;
pub use self::da_precision_ as da_precision;
pub const da_order__row_major: da_order_ = 0;
pub const da_order__column_major: da_order_ = 1;
pub type da_order_ = ::std::os::raw::c_int;
pub use self::da_order_ as da_order;
pub type da_int = i32;
pub const da_axis__da_axis_col: da_axis_ = 0;
pub const da_axis__da_axis_row: da_axis_ = 1;
pub const da_axis__da_axis_all: da_axis_ = 2;
pub type da_axis_ = ::std::os::raw::c_int;
pub use self::da_axis_ as da_axis;
pub const da_quantile_type__da_quantile_type_1: da_quantile_type_ = 0;
pub const da_quantile_type__da_quantile_type_2: da_quantile_type_ = 1;
pub const da_quantile_type__da_quantile_type_3: da_quantile_type_ = 2;
pub const da_quantile_type__da_quantile_type_4: da_quantile_type_ = 3;
pub const da_quantile_type__da_quantile_type_5: da_quantile_type_ = 4;
pub const da_quantile_type__da_quantile_type_6: da_quantile_type_ = 5;
pub const da_quantile_type__da_quantile_type_7: da_quantile_type_ = 6;
pub const da_quantile_type__da_quantile_type_8: da_quantile_type_ = 7;
pub const da_quantile_type__da_quantile_type_9: da_quantile_type_ = 8;
pub type da_quantile_type_ = ::std::os::raw::c_int;
pub use self::da_quantile_type_ as da_quantile_type;
extern "C" {
    pub fn da_mean_d(
        order: da_order,
        axis: da_axis,
        n_rows: da_int,
        n_cols: da_int,
        X: *const f64,
        ldx: da_int,
        mean: *mut f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_mean_s(
        order: da_order,
        axis: da_axis,
        n_rows: da_int,
        n_cols: da_int,
        X: *const f32,
        ldx: da_int,
        mean: *mut f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_geometric_mean_d(
        order: da_order,
        axis: da_axis,
        n_rows: da_int,
        n_cols: da_int,
        X: *const f64,
        ldx: da_int,
        geometric_mean: *mut f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_geometric_mean_s(
        order: da_order,
        axis: da_axis,
        n_rows: da_int,
        n_cols: da_int,
        X: *const f32,
        ldx: da_int,
        geometric_mean: *mut f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_harmonic_mean_d(
        order: da_order,
        axis: da_axis,
        n_rows: da_int,
        n_cols: da_int,
        X: *const f64,
        ldx: da_int,
        harmonic_mean: *mut f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_harmonic_mean_s(
        order: da_order,
        axis: da_axis,
        n_rows: da_int,
        n_cols: da_int,
        X: *const f32,
        ldx: da_int,
        harmonic_mean: *mut f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_variance_d(
        order: da_order,
        axis: da_axis,
        n_rows: da_int,
        n_cols: da_int,
        X: *const f64,
        ldx: da_int,
        dof: da_int,
        mean: *mut f64,
        variance: *mut f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_variance_s(
        order: da_order,
        axis: da_axis,
        n_rows: da_int,
        n_cols: da_int,
        X: *const f32,
        ldx: da_int,
        dof: da_int,
        mean: *mut f32,
        variance: *mut f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_skewness_d(
        order: da_order,
        axis: da_axis,
        n_rows: da_int,
        n_cols: da_int,
        X: *const f64,
        ldx: da_int,
        mean: *mut f64,
        variance: *mut f64,
        skewness: *mut f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_skewness_s(
        order: da_order,
        axis: da_axis,
        n_rows: da_int,
        n_cols: da_int,
        X: *const f32,
        ldx: da_int,
        mean: *mut f32,
        variance: *mut f32,
        skewness: *mut f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_kurtosis_d(
        order: da_order,
        axis: da_axis,
        n_rows: da_int,
        n_cols: da_int,
        X: *const f64,
        ldx: da_int,
        mean: *mut f64,
        variance: *mut f64,
        kurtosis: *mut f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_kurtosis_s(
        order: da_order,
        axis: da_axis,
        n_rows: da_int,
        n_cols: da_int,
        X: *const f32,
        ldx: da_int,
        mean: *mut f32,
        variance: *mut f32,
        kurtosis: *mut f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_moment_d(
        order: da_order,
        axis: da_axis,
        n_rows: da_int,
        n_cols: da_int,
        X: *const f64,
        ldx: da_int,
        k: da_int,
        use_precomputed_mean: da_int,
        mean: *mut f64,
        moment: *mut f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_moment_s(
        order: da_order,
        axis: da_axis,
        n_rows: da_int,
        n_cols: da_int,
        X: *const f32,
        ldx: da_int,
        k: da_int,
        use_precomputed_mean: da_int,
        mean: *mut f32,
        moment: *mut f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_quantile_d(
        order: da_order,
        axis: da_axis,
        n_rows: da_int,
        n_cols: da_int,
        X: *const f64,
        ldx: da_int,
        q: f64,
        quantile: *mut f64,
        quantile_type: da_quantile_type,
    ) -> da_status;
}
extern "C" {
    pub fn da_quantile_s(
        order: da_order,
        axis: da_axis,
        n_rows: da_int,
        n_cols: da_int,
        X: *const f32,
        ldx: da_int,
        q: f32,
        quantile: *mut f32,
        quantile_type: da_quantile_type,
    ) -> da_status;
}
extern "C" {
    pub fn da_five_point_summary_d(
        order: da_order,
        axis: da_axis,
        n_rows: da_int,
        n_cols: da_int,
        X: *const f64,
        ldx: da_int,
        minimum: *mut f64,
        lower_hinge: *mut f64,
        median: *mut f64,
        upper_hinge: *mut f64,
        maximum: *mut f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_five_point_summary_s(
        order: da_order,
        axis: da_axis,
        n_rows: da_int,
        n_cols: da_int,
        X: *const f32,
        ldx: da_int,
        minimum: *mut f32,
        lower_hinge: *mut f32,
        median: *mut f32,
        upper_hinge: *mut f32,
        maximum: *mut f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_standardize_d(
        order: da_order,
        axis: da_axis,
        n_rows: da_int,
        n_cols: da_int,
        X: *mut f64,
        ldx: da_int,
        dof: da_int,
        mode: da_int,
        shift: *mut f64,
        scale: *mut f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_standardize_s(
        order: da_order,
        axis: da_axis,
        n_rows: da_int,
        n_cols: da_int,
        X: *mut f32,
        ldx: da_int,
        dof: da_int,
        mode: da_int,
        shift: *mut f32,
        scale: *mut f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_covariance_matrix_d(
        order: da_order,
        n_rows: da_int,
        n_cols: da_int,
        X: *const f64,
        ldx: da_int,
        dof: da_int,
        cov: *mut f64,
        ldcov: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_covariance_matrix_s(
        order: da_order,
        n_rows: da_int,
        n_cols: da_int,
        X: *const f32,
        ldx: da_int,
        dof: da_int,
        cov: *mut f32,
        ldcov: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_correlation_matrix_d(
        order: da_order,
        n_rows: da_int,
        n_cols: da_int,
        X: *const f64,
        ldx: da_int,
        corr: *mut f64,
        ldcorr: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_correlation_matrix_s(
        order: da_order,
        n_rows: da_int,
        n_cols: da_int,
        X: *const f32,
        ldx: da_int,
        corr: *mut f32,
        ldcorr: da_int,
    ) -> da_status;
}
pub const da_handle_type__da_handle_uninitialized: da_handle_type_ = 0;
pub const da_handle_type__da_handle_linmod: da_handle_type_ = 1;
pub const da_handle_type__da_handle_pca: da_handle_type_ = 2;
pub const da_handle_type__da_handle_kmeans: da_handle_type_ = 3;
pub const da_handle_type__da_handle_dbscan: da_handle_type_ = 4;
pub const da_handle_type__da_handle_decision_tree: da_handle_type_ = 5;
pub const da_handle_type__da_handle_decision_forest: da_handle_type_ = 6;
pub const da_handle_type__da_handle_nlls: da_handle_type_ = 7;
pub const da_handle_type__da_handle_knn: da_handle_type_ = 8;
pub const da_handle_type__da_handle_svm: da_handle_type_ = 9;
pub type da_handle_type_ = ::std::os::raw::c_int;
pub use self::da_handle_type_ as da_handle_type;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _da_handle {
    _unused: [u8; 0],
}
pub type da_handle = *mut _da_handle;
extern "C" {
    pub fn da_handle_init_d(handle: *mut da_handle, handle_type: da_handle_type) -> da_status;
}
extern "C" {
    pub fn da_handle_init_s(handle: *mut da_handle, handle_type: da_handle_type) -> da_status;
}
extern "C" {
    pub fn da_handle_print_error_message(handle: da_handle) -> da_status;
}
extern "C" {
    pub fn da_handle_destroy(handle: *mut da_handle);
}
extern "C" {
    pub fn da_handle_get_error_message(
        handle: da_handle,
        message: *mut *mut ::std::os::raw::c_char,
    ) -> da_status;
}
extern "C" {
    pub fn da_handle_get_error_severity(handle: da_handle, severity: *mut da_severity)
        -> da_status;
}
extern "C" {
    pub fn da_handle_refresh(handle: da_handle);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _da_datastore {
    _unused: [u8; 0],
}
pub type da_datastore = *mut _da_datastore;
extern "C" {
    pub fn da_datastore_init(store: *mut da_datastore) -> da_status;
}
extern "C" {
    pub fn da_datastore_print_error_message(store: da_datastore) -> da_status;
}
extern "C" {
    pub fn da_datastore_destroy(store: *mut da_datastore);
}
extern "C" {
    pub fn da_data_print_options(store: da_datastore) -> da_status;
}
extern "C" {
    pub fn da_data_hconcat(store1: *mut da_datastore, store2: *mut da_datastore) -> da_status;
}
extern "C" {
    pub fn da_data_load_col_int(
        store: da_datastore,
        n_rows: da_int,
        n_cols: da_int,
        block: *mut da_int,
        order: da_order,
        copy_data: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_load_col_real_d(
        store: da_datastore,
        n_rows: da_int,
        n_cols: da_int,
        block: *mut f64,
        order: da_order,
        copy_data: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_load_col_real_s(
        store: da_datastore,
        n_rows: da_int,
        n_cols: da_int,
        block: *mut f32,
        order: da_order,
        copy_data: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_load_col_uint8(
        store: da_datastore,
        n_rows: da_int,
        n_cols: da_int,
        block: *mut u8,
        order: da_order,
        copy_data: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_load_col_str(
        store: da_datastore,
        n_rows: da_int,
        n_cols: da_int,
        block: *mut *const ::std::os::raw::c_char,
        order: da_order,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_load_row_int(
        store: da_datastore,
        n_rows: da_int,
        n_cols: da_int,
        block: *mut da_int,
        order: da_order,
        copy_data: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_load_row_real_d(
        store: da_datastore,
        n_rows: da_int,
        n_cols: da_int,
        block: *mut f64,
        order: da_order,
        copy_data: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_load_row_real_s(
        store: da_datastore,
        n_rows: da_int,
        n_cols: da_int,
        block: *mut f32,
        order: da_order,
        copy_data: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_load_row_uint8(
        store: da_datastore,
        n_rows: da_int,
        n_cols: da_int,
        block: *mut u8,
        order: da_order,
        copy_data: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_load_row_str(
        store: da_datastore,
        n_rows: da_int,
        n_cols: da_int,
        block: *mut *const ::std::os::raw::c_char,
        order: da_order,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_load_from_csv(
        store: da_datastore,
        filename: *const ::std::os::raw::c_char,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_select_columns(
        store: da_datastore,
        key: *const ::std::os::raw::c_char,
        lbound: da_int,
        ubound: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_select_rows(
        store: da_datastore,
        key: *const ::std::os::raw::c_char,
        lbound: da_int,
        ubound: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_select_slice(
        store: da_datastore,
        key: *const ::std::os::raw::c_char,
        row_lbound: da_int,
        row_ubound: da_int,
        col_lbound: da_int,
        col_ubound: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_select_non_missing(
        store: da_datastore,
        key: *const ::std::os::raw::c_char,
        full_rows: u8,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_select_remove_columns(
        store: da_datastore,
        key: *const ::std::os::raw::c_char,
        lbound: da_int,
        ubound: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_select_remove_rows(
        store: da_datastore,
        key: *const ::std::os::raw::c_char,
        lbound: da_int,
        ubound: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_extract_column_int(
        store: da_datastore,
        idx: da_int,
        dim: da_int,
        col: *mut da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_extract_column_real_s(
        store: da_datastore,
        idx: da_int,
        dim: da_int,
        col: *mut f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_extract_column_real_d(
        store: da_datastore,
        idx: da_int,
        dim: da_int,
        col: *mut f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_extract_column_uint8(
        store: da_datastore,
        idx: da_int,
        dim: da_int,
        col: *mut u8,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_extract_column_str(
        store: da_datastore,
        idx: da_int,
        dim: da_int,
        col: *mut *mut ::std::os::raw::c_char,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_extract_selection_int(
        store: da_datastore,
        key: *const ::std::os::raw::c_char,
        order: da_order,
        data: *mut da_int,
        lddata: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_extract_selection_real_d(
        store: da_datastore,
        key: *const ::std::os::raw::c_char,
        order: da_order,
        data: *mut f64,
        lddata: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_extract_selection_real_s(
        store: da_datastore,
        key: *const ::std::os::raw::c_char,
        order: da_order,
        data: *mut f32,
        lddata: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_extract_selection_uint8(
        store: da_datastore,
        key: *const ::std::os::raw::c_char,
        order: da_order,
        data: *mut u8,
        lddata: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_label_column(
        store: da_datastore,
        label: *const ::std::os::raw::c_char,
        col_idx: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_get_col_idx(
        store: da_datastore,
        label: *const ::std::os::raw::c_char,
        col_idx: *mut da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_get_col_label(
        store: da_datastore,
        col_idx: da_int,
        label_sz: *mut da_int,
        label: *mut ::std::os::raw::c_char,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_get_n_rows(store: da_datastore, n_rows: *mut da_int) -> da_status;
}
extern "C" {
    pub fn da_data_get_n_cols(store: da_datastore, n_cols: *mut da_int) -> da_status;
}
extern "C" {
    pub fn da_data_get_element_int(
        store: da_datastore,
        i: da_int,
        j: da_int,
        elem: *mut da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_get_element_real_d(
        store: da_datastore,
        i: da_int,
        j: da_int,
        elem: *mut f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_get_element_real_s(
        store: da_datastore,
        i: da_int,
        j: da_int,
        elem: *mut f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_get_element_uint8(
        store: da_datastore,
        i: da_int,
        j: da_int,
        elem: *mut u8,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_set_element_int(
        store: da_datastore,
        i: da_int,
        j: da_int,
        elem: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_set_element_real_d(
        store: da_datastore,
        i: da_int,
        j: da_int,
        elem: f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_set_element_real_s(
        store: da_datastore,
        i: da_int,
        j: da_int,
        elem: f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_data_set_element_uint8(
        store: da_datastore,
        i: da_int,
        j: da_int,
        elem: u8,
    ) -> da_status;
}
extern "C" {
    pub fn da_read_csv_d(
        store: da_datastore,
        filename: *const ::std::os::raw::c_char,
        A: *mut *mut f64,
        n_rows: *mut da_int,
        n_cols: *mut da_int,
        headings: *mut *mut *mut ::std::os::raw::c_char,
    ) -> da_status;
}
extern "C" {
    pub fn da_read_csv_s(
        store: da_datastore,
        filename: *const ::std::os::raw::c_char,
        A: *mut *mut f32,
        n_rows: *mut da_int,
        n_cols: *mut da_int,
        headings: *mut *mut *mut ::std::os::raw::c_char,
    ) -> da_status;
}
extern "C" {
    pub fn da_read_csv_int(
        store: da_datastore,
        filename: *const ::std::os::raw::c_char,
        A: *mut *mut da_int,
        n_rows: *mut da_int,
        n_cols: *mut da_int,
        headings: *mut *mut *mut ::std::os::raw::c_char,
    ) -> da_status;
}
extern "C" {
    pub fn da_read_csv_uint8(
        store: da_datastore,
        filename: *const ::std::os::raw::c_char,
        A: *mut *mut u8,
        n_rows: *mut da_int,
        n_cols: *mut da_int,
        headings: *mut *mut *mut ::std::os::raw::c_char,
    ) -> da_status;
}
extern "C" {
    pub fn da_read_csv_string(
        store: da_datastore,
        filename: *const ::std::os::raw::c_char,
        A: *mut *mut *mut ::std::os::raw::c_char,
        n_rows: *mut da_int,
        n_cols: *mut da_int,
        headings: *mut *mut *mut ::std::os::raw::c_char,
    ) -> da_status;
}
extern "C" {
    pub fn da_delete_string_array(S: *mut *mut *mut ::std::os::raw::c_char, n: da_int)
        -> da_status;
}
extern "C" {
    pub fn da_dbscan_set_data_d(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        A: *const f64,
        lda: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_dbscan_set_data_s(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        A: *const f32,
        lda: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_dbscan_compute_d(handle: da_handle) -> da_status;
}
extern "C" {
    pub fn da_dbscan_compute_s(handle: da_handle) -> da_status;
}
extern "C" {
    pub fn da_tree_set_training_data_d(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        n_class: da_int,
        X: *const f64,
        ldx: da_int,
        y: *const da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_tree_set_training_data_s(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        n_class: da_int,
        X: *const f32,
        ldx: da_int,
        y: *const da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_forest_set_training_data_d(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        n_class: da_int,
        X: *const f64,
        ldx: da_int,
        y: *const da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_forest_set_training_data_s(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        n_class: da_int,
        X: *const f32,
        ldx: da_int,
        y: *const da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_tree_fit_d(handle: da_handle) -> da_status;
}
extern "C" {
    pub fn da_tree_fit_s(handle: da_handle) -> da_status;
}
extern "C" {
    pub fn da_forest_fit_d(handle: da_handle) -> da_status;
}
extern "C" {
    pub fn da_forest_fit_s(handle: da_handle) -> da_status;
}
extern "C" {
    pub fn da_tree_predict_d(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X_test: *const f64,
        ldx_test: da_int,
        y_pred: *mut da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_tree_predict_s(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X_test: *const f32,
        ldx_test: da_int,
        y_pred: *mut da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_tree_predict_proba_d(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X_test: *const f64,
        ldx_test: da_int,
        y_proba: *mut f64,
        n_class: da_int,
        ldy: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_tree_predict_proba_s(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X_test: *const f32,
        ldx_test: da_int,
        y_proba: *mut f32,
        n_class: da_int,
        ldy: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_tree_predict_log_proba_d(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X_test: *const f64,
        ldx_test: da_int,
        y_log_proba: *mut f64,
        n_class: da_int,
        ldy: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_tree_predict_log_proba_s(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X_test: *const f32,
        ldx_test: da_int,
        y_log_proba: *mut f32,
        n_class: da_int,
        ldy: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_forest_predict_d(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X_test: *const f64,
        ldx_test: da_int,
        y_pred: *mut da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_forest_predict_s(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X_test: *const f32,
        ldx_test: da_int,
        y_pred: *mut da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_forest_predict_proba_d(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X_test: *const f64,
        ldx_test: da_int,
        y_proba: *mut f64,
        n_class: da_int,
        ldy: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_forest_predict_proba_s(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X_test: *const f32,
        ldx_test: da_int,
        y_proba: *mut f32,
        n_class: da_int,
        ldy: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_forest_predict_log_proba_d(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X_test: *const f64,
        ldx_test: da_int,
        y_log_proba: *mut f64,
        n_class: da_int,
        ldy: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_forest_predict_log_proba_s(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X_test: *const f32,
        ldx_test: da_int,
        y_log_proba: *mut f32,
        n_class: da_int,
        ldy: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_tree_score_d(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X_test: *const f64,
        ldx_test: da_int,
        y_test: *const da_int,
        mean_accuracy: *mut f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_tree_score_s(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X_test: *const f32,
        ldx_test: da_int,
        y_test: *const da_int,
        mean_accuracy: *mut f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_forest_score_d(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X_test: *const f64,
        ldx_test: da_int,
        y_test: *const da_int,
        mean_accuracy: *mut f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_forest_score_s(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X_test: *const f32,
        ldx_test: da_int,
        y_test: *const da_int,
        mean_accuracy: *mut f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_rbf_kernel_d(
        order: da_order,
        m: da_int,
        n: da_int,
        k: da_int,
        X: *const f64,
        ldx: da_int,
        Y: *const f64,
        ldy: da_int,
        D: *mut f64,
        ldd: da_int,
        gamma: f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_rbf_kernel_s(
        order: da_order,
        m: da_int,
        n: da_int,
        k: da_int,
        X: *const f32,
        ldx: da_int,
        Y: *const f32,
        ldy: da_int,
        D: *mut f32,
        ldd: da_int,
        gamma: f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_linear_kernel_d(
        order: da_order,
        m: da_int,
        n: da_int,
        k: da_int,
        X: *const f64,
        ldx: da_int,
        Y: *const f64,
        ldy: da_int,
        D: *mut f64,
        ldd: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_linear_kernel_s(
        order: da_order,
        m: da_int,
        n: da_int,
        k: da_int,
        X: *const f32,
        ldx: da_int,
        Y: *const f32,
        ldy: da_int,
        D: *mut f32,
        ldd: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_polynomial_kernel_d(
        order: da_order,
        m: da_int,
        n: da_int,
        k: da_int,
        X: *const f64,
        ldx: da_int,
        Y: *const f64,
        ldy: da_int,
        D: *mut f64,
        ldd: da_int,
        gamma: f64,
        degree: da_int,
        coef0: f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_polynomial_kernel_s(
        order: da_order,
        m: da_int,
        n: da_int,
        k: da_int,
        X: *const f32,
        ldx: da_int,
        Y: *const f32,
        ldy: da_int,
        D: *mut f32,
        ldd: da_int,
        gamma: f32,
        degree: da_int,
        coef0: f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_sigmoid_kernel_d(
        order: da_order,
        m: da_int,
        n: da_int,
        k: da_int,
        X: *const f64,
        ldx: da_int,
        Y: *const f64,
        ldy: da_int,
        D: *mut f64,
        ldd: da_int,
        gamma: f64,
        coef0: f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_sigmoid_kernel_s(
        order: da_order,
        m: da_int,
        n: da_int,
        k: da_int,
        X: *const f32,
        ldx: da_int,
        Y: *const f32,
        ldy: da_int,
        D: *mut f32,
        ldd: da_int,
        gamma: f32,
        coef0: f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_kmeans_set_data_d(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        A: *const f64,
        lda: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_kmeans_set_data_s(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        A: *const f32,
        lda: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_kmeans_set_init_centres_d(handle: da_handle, C: *const f64, ldc: da_int)
        -> da_status;
}
extern "C" {
    pub fn da_kmeans_set_init_centres_s(handle: da_handle, C: *const f32, ldc: da_int)
        -> da_status;
}
extern "C" {
    pub fn da_kmeans_compute_d(handle: da_handle) -> da_status;
}
extern "C" {
    pub fn da_kmeans_compute_s(handle: da_handle) -> da_status;
}
extern "C" {
    pub fn da_kmeans_transform_d(
        handle: da_handle,
        m_samples: da_int,
        m_features: da_int,
        X: *const f64,
        ldx: da_int,
        X_transform: *mut f64,
        ldx_transform: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_kmeans_transform_s(
        handle: da_handle,
        m_samples: da_int,
        m_features: da_int,
        X: *const f32,
        ldx: da_int,
        X_transform: *mut f32,
        ldx_transform: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_kmeans_predict_d(
        handle: da_handle,
        k_samples: da_int,
        k_features: da_int,
        Y: *const f64,
        ldy: da_int,
        Y_labels: *mut da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_kmeans_predict_s(
        handle: da_handle,
        k_samples: da_int,
        k_features: da_int,
        Y: *const f32,
        ldy: da_int,
        Y_labels: *mut da_int,
    ) -> da_status;
}
pub const da_knn_algorithm__da_brute_force: da_knn_algorithm_ = 0;
pub type da_knn_algorithm_ = ::std::os::raw::c_int;
pub use self::da_knn_algorithm_ as da_knn_algorithm;
pub const da_knn_weights__da_knn_uniform: da_knn_weights_ = 0;
pub const da_knn_weights__da_knn_distance: da_knn_weights_ = 1;
pub type da_knn_weights_ = ::std::os::raw::c_int;
pub use self::da_knn_weights_ as da_knn_weights;
extern "C" {
    pub fn da_knn_set_training_data_d(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X_train: *const f64,
        ldx_train: da_int,
        y_train: *const da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_knn_set_training_data_s(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X_train: *const f32,
        ldx_train: da_int,
        y_train: *const da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_knn_kneighbors_d(
        handle: da_handle,
        n_queries: da_int,
        n_features: da_int,
        X_test: *const f64,
        ldx_test: da_int,
        n_ind: *mut da_int,
        n_dist: *mut f64,
        k: da_int,
        return_distance: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_knn_kneighbors_s(
        handle: da_handle,
        n_queries: da_int,
        n_features: da_int,
        X_test: *const f32,
        ldx_test: da_int,
        n_ind: *mut da_int,
        n_dist: *mut f32,
        k: da_int,
        return_distance: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_knn_classes_d(
        handle: da_handle,
        n_classes: *mut da_int,
        classes: *mut da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_knn_classes_s(
        handle: da_handle,
        n_classes: *mut da_int,
        classes: *mut da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_knn_predict_proba_d(
        handle: da_handle,
        n_queries: da_int,
        n_features: da_int,
        X_test: *const f64,
        ldx_test: da_int,
        proba: *mut f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_knn_predict_proba_s(
        handle: da_handle,
        n_queries: da_int,
        n_features: da_int,
        X_test: *const f32,
        ldx_test: da_int,
        proba: *mut f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_knn_predict_d(
        handle: da_handle,
        n_queries: da_int,
        n_features: da_int,
        X_test: *const f64,
        ldx_test: da_int,
        y_test: *mut da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_knn_predict_s(
        handle: da_handle,
        n_queries: da_int,
        n_features: da_int,
        X_test: *const f32,
        ldx_test: da_int,
        y_test: *mut da_int,
    ) -> da_status;
}
pub const linmod_model__linmod_model_undefined: linmod_model_ = 0;
pub const linmod_model__linmod_model_mse: linmod_model_ = 1;
pub const linmod_model__linmod_model_logistic: linmod_model_ = 2;
pub type linmod_model_ = ::std::os::raw::c_int;
pub use self::linmod_model_ as linmod_model;
extern "C" {
    pub fn da_linmod_select_model_s(handle: da_handle, mod_: linmod_model) -> da_status;
}
extern "C" {
    pub fn da_linmod_select_model_d(handle: da_handle, mod_: linmod_model) -> da_status;
}
extern "C" {
    pub fn da_linmod_define_features_d(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X: *const f64,
        y: *const f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_linmod_define_features_s(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X: *const f32,
        y: *const f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_linmod_fit_d(handle: da_handle) -> da_status;
}
extern "C" {
    pub fn da_linmod_fit_s(handle: da_handle) -> da_status;
}
extern "C" {
    pub fn da_linmod_fit_start_d(
        handle: da_handle,
        n_coefs: da_int,
        coefs: *const f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_linmod_fit_start_s(
        handle: da_handle,
        n_coefs: da_int,
        coefs: *const f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_linmod_evaluate_model_d(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X: *const f64,
        predictions: *mut f64,
        observations: *mut f64,
        loss: *mut f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_linmod_evaluate_model_s(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X: *const f32,
        predictions: *mut f32,
        observations: *mut f32,
        loss: *mut f32,
    ) -> da_status;
}
pub const da_metric__da_euclidean: da_metric_ = 0;
pub const da_metric__da_l2: da_metric_ = 0;
pub const da_metric__da_sqeuclidean: da_metric_ = 1;
pub const da_metric__da_minkowski: da_metric_ = 2;
pub const da_metric__da_manhattan: da_metric_ = 3;
pub const da_metric__da_l1: da_metric_ = 3;
pub const da_metric__da_cityblock: da_metric_ = 3;
pub const da_metric__da_cosine: da_metric_ = 4;
pub type da_metric_ = ::std::os::raw::c_int;
pub use self::da_metric_ as da_metric;
pub const da_data_types__da_all_finite: da_data_types_ = 0;
pub const da_data_types__da_allow_infinite: da_data_types_ = 1;
pub const da_data_types__da_allow_NaN: da_data_types_ = 2;
pub type da_data_types_ = ::std::os::raw::c_int;
pub use self::da_data_types_ as da_data_types;
extern "C" {
    pub fn da_pairwise_distances_d(
        order: da_order,
        m: da_int,
        n: da_int,
        k: da_int,
        X: *const f64,
        ldx: da_int,
        Y: *const f64,
        ldy: da_int,
        D: *mut f64,
        ldd: da_int,
        p: f64,
        metric: da_metric,
    ) -> da_status;
}
extern "C" {
    pub fn da_pairwise_distances_s(
        order: da_order,
        m: da_int,
        n: da_int,
        k: da_int,
        X: *const f32,
        ldx: da_int,
        Y: *const f32,
        ldy: da_int,
        D: *mut f32,
        ldd: da_int,
        p: f32,
        metric: da_metric,
    ) -> da_status;
}
extern "C" {
    pub fn da_parallel_check() -> da_status;
}
extern "C" {
    pub fn da_get_version() -> *const ::std::os::raw::c_char;
}
pub type da_resfun_t_s = ::std::option::Option<
    unsafe extern "C" fn(
        n_coef: da_int,
        n_res: da_int,
        data: *mut ::std::os::raw::c_void,
        x: *const f32,
        res: *mut f32,
    ) -> da_int,
>;
pub type da_resfun_t_d = ::std::option::Option<
    unsafe extern "C" fn(
        n_coef: da_int,
        n_res: da_int,
        data: *mut ::std::os::raw::c_void,
        x: *const f64,
        res: *mut f64,
    ) -> da_int,
>;
pub type da_resgrd_t_s = ::std::option::Option<
    unsafe extern "C" fn(
        n_coef: da_int,
        n_res: da_int,
        data: *mut ::std::os::raw::c_void,
        x: *const f32,
        jac: *mut f32,
    ) -> da_int,
>;
pub type da_resgrd_t_d = ::std::option::Option<
    unsafe extern "C" fn(
        n_coef: da_int,
        n_res: da_int,
        data: *mut ::std::os::raw::c_void,
        x: *const f64,
        jac: *mut f64,
    ) -> da_int,
>;
pub type da_reshes_t_s = ::std::option::Option<
    unsafe extern "C" fn(
        n_coef: da_int,
        n_res: da_int,
        data: *mut ::std::os::raw::c_void,
        x: *const f32,
        wr: *const f32,
        hes: *mut f32,
    ) -> da_int,
>;
pub type da_reshes_t_d = ::std::option::Option<
    unsafe extern "C" fn(
        n_coef: da_int,
        n_res: da_int,
        data: *mut ::std::os::raw::c_void,
        x: *const f64,
        wr: *const f64,
        hes: *mut f64,
    ) -> da_int,
>;
pub type da_reshp_t_s = ::std::option::Option<
    unsafe extern "C" fn(
        n_coef: da_int,
        n_res: da_int,
        x: *const f32,
        y: *const f32,
        hp: *mut f32,
        data: *mut ::std::os::raw::c_void,
    ) -> da_int,
>;
pub type da_reshp_t_d = ::std::option::Option<
    unsafe extern "C" fn(
        n_coef: da_int,
        n_res: da_int,
        x: *const f64,
        y: *const f64,
        hp: *mut f64,
        data: *mut ::std::os::raw::c_void,
    ) -> da_int,
>;
extern "C" {
    pub fn da_nlls_define_residuals_d(
        handle: da_handle,
        n_coef: da_int,
        n_res: da_int,
        resfun: da_resfun_t_d,
        resgrd: da_resgrd_t_d,
        reshes: da_reshes_t_d,
        reshp: da_reshp_t_d,
    ) -> da_status;
}
extern "C" {
    pub fn da_nlls_define_residuals_s(
        handle: da_handle,
        n_coef: da_int,
        n_res: da_int,
        resfun: da_resfun_t_s,
        resgrd: da_resgrd_t_s,
        reshes: da_reshes_t_s,
        reshp: da_reshp_t_s,
    ) -> da_status;
}
extern "C" {
    pub fn da_nlls_define_bounds_d(
        handle: da_handle,
        n_coef: da_int,
        lower: *mut f64,
        upper: *mut f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_nlls_define_bounds_s(
        handle: da_handle,
        n_coef: da_int,
        lower: *mut f32,
        upper: *mut f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_nlls_define_weights_d(
        handle: da_handle,
        n_res: da_int,
        weights: *mut f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_nlls_define_weights_s(
        handle: da_handle,
        n_res: da_int,
        weights: *mut f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_nlls_fit_d(
        handle: da_handle,
        n_coef: da_int,
        coef: *mut f64,
        udata: *mut ::std::os::raw::c_void,
    ) -> da_status;
}
extern "C" {
    pub fn da_nlls_fit_s(
        handle: da_handle,
        n_coef: da_int,
        coef: *mut f32,
        udata: *mut ::std::os::raw::c_void,
    ) -> da_status;
}
pub const da_optim_info_t__info_objective: da_optim_info_t_ = 0;
pub const da_optim_info_t__info_grad_norm: da_optim_info_t_ = 1;
pub const da_optim_info_t__info_iter: da_optim_info_t_ = 2;
pub const da_optim_info_t__info_time: da_optim_info_t_ = 3;
pub const da_optim_info_t__info_nevalf: da_optim_info_t_ = 4;
pub const da_optim_info_t__info_inorm: da_optim_info_t_ = 5;
pub const da_optim_info_t__info_inorm_init: da_optim_info_t_ = 6;
pub const da_optim_info_t__info_ncheap: da_optim_info_t_ = 7;
pub const da_optim_info_t__info_nevalg: da_optim_info_t_ = 8;
pub const da_optim_info_t__info_nevalh: da_optim_info_t_ = 9;
pub const da_optim_info_t__info_nevalhp: da_optim_info_t_ = 10;
pub const da_optim_info_t__info_scl_grad_norm: da_optim_info_t_ = 11;
pub const da_optim_info_t__info_nevalfd: da_optim_info_t_ = 12;
pub const da_optim_info_t__info_optim: da_optim_info_t_ = 13;
pub const da_optim_info_t__info_optimcnt: da_optim_info_t_ = 14;
pub const da_optim_info_t__info_number: da_optim_info_t_ = 15;
pub type da_optim_info_t_ = ::std::os::raw::c_int;
pub use self::da_optim_info_t_ as da_optim_info_t;
extern "C" {
    pub fn da_options_set_int(
        handle: da_handle,
        option: *const ::std::os::raw::c_char,
        value: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_options_set_string(
        handle: da_handle,
        option: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> da_status;
}
extern "C" {
    pub fn da_options_set_real_s(
        handle: da_handle,
        option: *const ::std::os::raw::c_char,
        value: f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_options_set_real_d(
        handle: da_handle,
        option: *const ::std::os::raw::c_char,
        value: f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_options_get_int(
        handle: da_handle,
        option: *const ::std::os::raw::c_char,
        value: *mut da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_options_get_real_s(
        handle: da_handle,
        option: *const ::std::os::raw::c_char,
        value: *mut f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_options_get_real_d(
        handle: da_handle,
        option: *const ::std::os::raw::c_char,
        value: *mut f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_options_get_string(
        handle: da_handle,
        option: *const ::std::os::raw::c_char,
        value: *mut ::std::os::raw::c_char,
        lvalue: *mut da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_options_get_string_key(
        handle: da_handle,
        option: *const ::std::os::raw::c_char,
        value: *mut ::std::os::raw::c_char,
        lvalue: *mut da_int,
        key: *mut da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_options_print(handle: da_handle) -> da_status;
}
extern "C" {
    pub fn da_datastore_options_set_int(
        store: da_datastore,
        option: *const ::std::os::raw::c_char,
        value: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_datastore_options_set_string(
        store: da_datastore,
        option: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> da_status;
}
extern "C" {
    pub fn da_datastore_options_set_real_s(
        store: da_datastore,
        option: *const ::std::os::raw::c_char,
        value: f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_datastore_options_set_real_d(
        store: da_datastore,
        option: *const ::std::os::raw::c_char,
        value: f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_datastore_options_get_int(
        store: da_datastore,
        option: *const ::std::os::raw::c_char,
        value: *mut da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_datastore_options_get_real_s(
        store: da_datastore,
        option: *const ::std::os::raw::c_char,
        value: *mut f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_datastore_options_get_real_d(
        store: da_datastore,
        option: *const ::std::os::raw::c_char,
        value: *mut f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_datastore_options_get_string(
        store: da_datastore,
        option: *const ::std::os::raw::c_char,
        value: *mut ::std::os::raw::c_char,
        lvalue: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_datastore_options_print(store: da_datastore) -> da_status;
}
extern "C" {
    pub fn da_pca_set_data_d(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        A: *const f64,
        lda: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_pca_set_data_s(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        A: *const f32,
        lda: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_pca_compute_d(handle: da_handle) -> da_status;
}
extern "C" {
    pub fn da_pca_compute_s(handle: da_handle) -> da_status;
}
extern "C" {
    pub fn da_pca_transform_d(
        handle: da_handle,
        m_samples: da_int,
        m_features: da_int,
        X: *const f64,
        ldx: da_int,
        X_transform: *mut f64,
        ldx_transform: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_pca_transform_s(
        handle: da_handle,
        m_samples: da_int,
        m_features: da_int,
        X: *const f32,
        ldx: da_int,
        X_transform: *mut f32,
        ldx_transform: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_pca_inverse_transform_d(
        handle: da_handle,
        k_samples: da_int,
        k_features: da_int,
        Y: *const f64,
        ldy: da_int,
        Y_inv_transform: *mut f64,
        ldy_inv_transform: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_pca_inverse_transform_s(
        handle: da_handle,
        k_samples: da_int,
        k_features: da_int,
        Y: *const f32,
        ldy: da_int,
        Y_inv_transform: *mut f32,
        ldy_inv_transform: da_int,
    ) -> da_status;
}
pub const da_result__da_rinfo: da_result_ = 1;
pub const da_result__da_linmod_coef: da_result_ = 101;
pub const da_result__da_pca_scores: da_result_ = 201;
pub const da_result__da_pca_variance: da_result_ = 202;
pub const da_result__da_pca_principal_components: da_result_ = 203;
pub const da_result__da_pca_total_variance: da_result_ = 204;
pub const da_result__da_pca_column_means: da_result_ = 205;
pub const da_result__da_pca_column_sdevs: da_result_ = 206;
pub const da_result__da_pca_u: da_result_ = 207;
pub const da_result__da_pca_sigma: da_result_ = 208;
pub const da_result__da_pca_vt: da_result_ = 209;
pub const da_result__da_kmeans_cluster_centres: da_result_ = 501;
pub const da_result__da_kmeans_labels: da_result_ = 502;
pub const da_result__da_dbscan_labels: da_result_ = 503;
pub const da_result__da_dbscan_n_clusters: da_result_ = 504;
pub const da_result__da_dbscan_n_core_samples: da_result_ = 505;
pub const da_result__da_dbscan_core_sample_indices: da_result_ = 506;
pub const da_result__da_knn_model_params: da_result_ = 601;
pub const da_result__da_svm_n_support_vectors: da_result_ = 701;
pub const da_result__da_svm_n_support_vectors_per_class: da_result_ = 702;
pub const da_result__da_svm_idx_support_vectors: da_result_ = 703;
pub const da_result__da_svm_n_iterations: da_result_ = 704;
pub const da_result__da_svm_support_vectors: da_result_ = 705;
pub const da_result__da_svm_bias: da_result_ = 706;
pub const da_result__da_svm_dual_coef: da_result_ = 707;
pub type da_result_ = ::std::os::raw::c_int;
pub use self::da_result_ as da_result;
extern "C" {
    pub fn da_handle_get_result_d(
        handle: da_handle,
        query: da_result,
        dim: *mut da_int,
        result: *mut f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_handle_get_result_s(
        handle: da_handle,
        query: da_result,
        dim: *mut da_int,
        result: *mut f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_handle_get_result_int(
        handle: da_handle,
        query: da_result,
        dim: *mut da_int,
        result: *mut da_int,
    ) -> da_status;
}
pub const da_svm_model__svm_undefined: da_svm_model_ = 0;
pub const da_svm_model__svc: da_svm_model_ = 1;
pub const da_svm_model__nusvc: da_svm_model_ = 2;
pub const da_svm_model__svr: da_svm_model_ = 3;
pub const da_svm_model__nusvr: da_svm_model_ = 4;
pub type da_svm_model_ = ::std::os::raw::c_int;
pub use self::da_svm_model_ as da_svm_model;
pub const da_svm_decision_function_shape__ovr: da_svm_decision_function_shape_ = 0;
pub const da_svm_decision_function_shape__ovo: da_svm_decision_function_shape_ = 1;
pub type da_svm_decision_function_shape_ = ::std::os::raw::c_int;
pub use self::da_svm_decision_function_shape_ as da_svm_decision_function_shape;
extern "C" {
    pub fn da_svm_select_model_d(handle: da_handle, mod_: da_svm_model) -> da_status;
}
extern "C" {
    pub fn da_svm_select_model_s(handle: da_handle, mod_: da_svm_model) -> da_status;
}
extern "C" {
    pub fn da_svm_set_data_d(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X: *const f64,
        ldx: da_int,
        y: *const f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_svm_set_data_s(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X: *const f32,
        ldx: da_int,
        y: *const f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_svm_compute_d(handle: da_handle) -> da_status;
}
extern "C" {
    pub fn da_svm_compute_s(handle: da_handle) -> da_status;
}
extern "C" {
    pub fn da_svm_predict_d(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X_test: *const f64,
        ldx_test: da_int,
        predictions: *mut f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_svm_predict_s(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X_test: *const f32,
        ldx_test: da_int,
        predictions: *mut f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_svm_decision_function_d(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X_test: *const f64,
        ldx_test: da_int,
        shape: da_svm_decision_function_shape,
        decision_values: *mut f64,
        ldd: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_svm_decision_function_s(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X_test: *const f32,
        ldx_test: da_int,
        shape: da_svm_decision_function_shape,
        decision_values: *mut f32,
        ldd: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_svm_score_d(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X_test: *const f64,
        ldx_test: da_int,
        y_test: *const f64,
        score: *mut f64,
    ) -> da_status;
}
extern "C" {
    pub fn da_svm_score_s(
        handle: da_handle,
        n_samples: da_int,
        n_features: da_int,
        X_test: *const f32,
        ldx_test: da_int,
        y_test: *const f32,
        score: *mut f32,
    ) -> da_status;
}
extern "C" {
    pub fn da_check_data_d(
        order: da_order,
        n_rows: da_int,
        n_cols: da_int,
        X: *const f64,
        ldx: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_check_data_s(
        order: da_order,
        n_rows: da_int,
        n_cols: da_int,
        X: *const f32,
        ldx: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_switch_order_copy_d(
        order_X: da_order,
        n_rows: da_int,
        n_cols: da_int,
        X: *const f64,
        ldx: da_int,
        Y: *mut f64,
        ldy: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_switch_order_copy_s(
        order_X: da_order,
        n_rows: da_int,
        n_cols: da_int,
        X: *const f32,
        ldx: da_int,
        Y: *mut f32,
        ldy: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_switch_order_in_place_d(
        order_X_in: da_order,
        n_rows: da_int,
        n_cols: da_int,
        X: *mut f64,
        ldx_in: da_int,
        ldx_out: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_switch_order_in_place_s(
        order_X_in: da_order,
        n_rows: da_int,
        n_cols: da_int,
        X: *mut f32,
        ldx_in: da_int,
        ldx_out: da_int,
    ) -> da_status;
}
extern "C" {
    pub fn da_get_arch_info(
        len: *mut da_int,
        arch: *mut ::std::os::raw::c_char,
        ns: *mut ::std::os::raw::c_char,
    ) -> da_status;
}
