/* automatically generated by rust-bindgen 0.69.5 */

#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _C_double_complex {
    pub _Val: [f64; 2usize],
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _C_float_complex {
    pub _Val: [f32; 2usize],
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct _C_ldouble_complex {
    pub _Val: [f64; 2usize],
}
pub type _Dcomplex = _C_double_complex;
pub type _Fcomplex = _C_float_complex;
pub type _Lcomplex = _C_ldouble_complex;
pub type fc32_t = _Fcomplex;
pub type fc64_t = _Dcomplex;
pub type fc128_t = _Lcomplex;
extern "C" {
    pub fn amd_cos(x: f64) -> f64;
}
extern "C" {
    pub fn amd_cosf(x: f32) -> f32;
}
extern "C" {
    pub fn amd_sin(x: f64) -> f64;
}
extern "C" {
    pub fn amd_sinf(x: f32) -> f32;
}
extern "C" {
    pub fn amd_tan(x: f64) -> f64;
}
extern "C" {
    pub fn amd_tanf(x: f32) -> f32;
}
extern "C" {
    pub fn amd_acos(x: f64) -> f64;
}
extern "C" {
    pub fn amd_acosf(x: f32) -> f32;
}
extern "C" {
    pub fn amd_asin(x: f64) -> f64;
}
extern "C" {
    pub fn amd_asinf(x: f32) -> f32;
}
extern "C" {
    pub fn amd_atan(x: f64) -> f64;
}
extern "C" {
    pub fn amd_atanf(x: f32) -> f32;
}
extern "C" {
    pub fn amd_atan2(x: f64, y: f64) -> f64;
}
extern "C" {
    pub fn amd_atan2f(x: f32, y: f32) -> f32;
}
extern "C" {
    pub fn amd_sincos(x: f64, s: *mut f64, c: *mut f64);
}
extern "C" {
    pub fn amd_sincosf(x: f32, s: *mut f32, c: *mut f32);
}
extern "C" {
    pub fn amd_cosh(x: f64) -> f64;
}
extern "C" {
    pub fn amd_coshf(x: f32) -> f32;
}
extern "C" {
    pub fn amd_sinh(x: f64) -> f64;
}
extern "C" {
    pub fn amd_sinhf(x: f32) -> f32;
}
extern "C" {
    pub fn amd_tanh(x: f64) -> f64;
}
extern "C" {
    pub fn amd_tanhf(x: f32) -> f32;
}
extern "C" {
    pub fn amd_acosh(x: f64) -> f64;
}
extern "C" {
    pub fn amd_acoshf(x: f32) -> f32;
}
extern "C" {
    pub fn amd_asinh(x: f64) -> f64;
}
extern "C" {
    pub fn amd_asinhf(x: f32) -> f32;
}
extern "C" {
    pub fn amd_atanh(x: f64) -> f64;
}
extern "C" {
    pub fn amd_atanhf(x: f32) -> f32;
}
extern "C" {
    pub fn amd_exp(x: f64) -> f64;
}
extern "C" {
    pub fn amd_expf(x: f32) -> f32;
}
extern "C" {
    pub fn amd_exp2(x: f64) -> f64;
}
extern "C" {
    pub fn amd_exp2f(x: f32) -> f32;
}
extern "C" {
    pub fn amd_exp10(x: f64) -> f64;
}
extern "C" {
    pub fn amd_exp10f(x: f32) -> f32;
}
extern "C" {
    pub fn amd_expm1(x: f64) -> f64;
}
extern "C" {
    pub fn amd_expm1f(x: f32) -> f32;
}
extern "C" {
    pub fn amd_log(x: f64) -> f64;
}
extern "C" {
    pub fn amd_logf(x: f32) -> f32;
}
extern "C" {
    pub fn amd_log2(x: f64) -> f64;
}
extern "C" {
    pub fn amd_log2f(x: f32) -> f32;
}
extern "C" {
    pub fn amd_log10(x: f64) -> f64;
}
extern "C" {
    pub fn amd_log10f(x: f32) -> f32;
}
extern "C" {
    pub fn amd_log1p(x: f64) -> f64;
}
extern "C" {
    pub fn amd_log1pf(x: f32) -> f32;
}
extern "C" {
    pub fn amd_logb(x: f64) -> f64;
}
extern "C" {
    pub fn amd_logbf(x: f32) -> f32;
}
extern "C" {
    pub fn amd_ilogb(x: f64) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn amd_ilogbf(x: f32) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn amd_modf(x: f64, iptr: *mut f64) -> f64;
}
extern "C" {
    pub fn amd_modff(x: f32, iptr: *mut f32) -> f32;
}
extern "C" {
    pub fn amd_frexp(value: f64, exp: *mut ::std::os::raw::c_int) -> f64;
}
extern "C" {
    pub fn amd_frexpf(value: f32, exp: *mut ::std::os::raw::c_int) -> f32;
}
extern "C" {
    pub fn amd_ldexp(x: f64, exp: ::std::os::raw::c_int) -> f64;
}
extern "C" {
    pub fn amd_ldexpf(x: f32, exp: ::std::os::raw::c_int) -> f32;
}
extern "C" {
    pub fn amd_scalbn(x: f64, n: ::std::os::raw::c_int) -> f64;
}
extern "C" {
    pub fn amd_scalbnf(x: f32, n: ::std::os::raw::c_int) -> f32;
}
extern "C" {
    pub fn amd_scalbln(x: f64, n: ::std::os::raw::c_long) -> f64;
}
extern "C" {
    pub fn amd_scalblnf(x: f32, n: ::std::os::raw::c_long) -> f32;
}
extern "C" {
    pub fn amd_pow(x: f64, y: f64) -> f64;
}
extern "C" {
    pub fn amd_powf(x: f32, y: f32) -> f32;
}
extern "C" {
    pub fn amd_cbrt(x: f64) -> f64;
}
extern "C" {
    pub fn amd_cbrtf(x: f32) -> f32;
}
extern "C" {
    pub fn amd_sqrt(x: f64) -> f64;
}
extern "C" {
    pub fn amd_sqrtf(x: f32) -> f32;
}
extern "C" {
    pub fn amd_hypot(x: f64, y: f64) -> f64;
}
extern "C" {
    pub fn amd_hypotf(x: f32, y: f32) -> f32;
}
extern "C" {
    pub fn amd_fabs(x: f64) -> f64;
}
extern "C" {
    pub fn amd_fabsf(x: f32) -> f32;
}
extern "C" {
    pub fn amd_ceil(x: f64) -> f64;
}
extern "C" {
    pub fn amd_ceilf(x: f32) -> f32;
}
extern "C" {
    pub fn amd_floor(x: f64) -> f64;
}
extern "C" {
    pub fn amd_floorf(x: f32) -> f32;
}
extern "C" {
    pub fn amd_trunc(x: f64) -> f64;
}
extern "C" {
    pub fn amd_truncf(x: f32) -> f32;
}
extern "C" {
    pub fn amd_lrint(x: f64) -> ::std::os::raw::c_long;
}
extern "C" {
    pub fn amd_lrintf(x: f32) -> ::std::os::raw::c_long;
}
extern "C" {
    pub fn amd_llrint(x: f64) -> ::std::os::raw::c_longlong;
}
extern "C" {
    pub fn amd_llrintf(x: f32) -> ::std::os::raw::c_longlong;
}
extern "C" {
    pub fn amd_rint(x: f64) -> f64;
}
extern "C" {
    pub fn amd_rintf(x: f32) -> f32;
}
extern "C" {
    pub fn amd_lround(d: f64) -> ::std::os::raw::c_long;
}
extern "C" {
    pub fn amd_lroundf(f: f32) -> ::std::os::raw::c_long;
}
extern "C" {
    pub fn amd_llround(d: f64) -> ::std::os::raw::c_longlong;
}
extern "C" {
    pub fn amd_llroundf(f: f32) -> ::std::os::raw::c_longlong;
}
extern "C" {
    pub fn amd_round(f: f64) -> f64;
}
extern "C" {
    pub fn amd_roundf(f: f32) -> f32;
}
extern "C" {
    pub fn amd_nearbyint(x: f64) -> f64;
}
extern "C" {
    pub fn amd_nearbyintf(x: f32) -> f32;
}
extern "C" {
    pub fn amd_fmod(x: f64, y: f64) -> f64;
}
extern "C" {
    pub fn amd_fmodf(x: f32, y: f32) -> f32;
}
extern "C" {
    pub fn amd_remainder(x: f64, y: f64) -> f64;
}
extern "C" {
    pub fn amd_remainderf(x: f32, y: f32) -> f32;
}
extern "C" {
    pub fn amd_remquo(x: f64, y: f64, quo: *mut ::std::os::raw::c_int) -> f64;
}
extern "C" {
    pub fn amd_remquof(x: f32, y: f32, quo: *mut ::std::os::raw::c_int) -> f32;
}
extern "C" {
    pub fn amd_copysign(x: f64, y: f64) -> f64;
}
extern "C" {
    pub fn amd_copysignf(x: f32, y: f32) -> f32;
}
extern "C" {
    pub fn amd_nextafter(x: f64, y: f64) -> f64;
}
extern "C" {
    pub fn amd_nextafterf(x: f32, y: f32) -> f32;
}
extern "C" {
    pub fn amd_nexttoward(x: f64, y: f64) -> f64;
}
extern "C" {
    pub fn amd_nexttowardf(x: f32, y: f64) -> f32;
}
extern "C" {
    pub fn amd_nan(tagp: *const ::std::os::raw::c_char) -> f64;
}
extern "C" {
    pub fn amd_nanf(tagp: *const ::std::os::raw::c_char) -> f32;
}
extern "C" {
    pub fn amd_finite(x: f64) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn amd_finitef(x: f32) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn amd_fdim(x: f64, y: f64) -> f64;
}
extern "C" {
    pub fn amd_fdimf(x: f32, y: f32) -> f32;
}
extern "C" {
    pub fn amd_fmax(x: f64, y: f64) -> f64;
}
extern "C" {
    pub fn amd_fmaxf(x: f32, y: f32) -> f32;
}
extern "C" {
    pub fn amd_fmin(x: f64, y: f64) -> f64;
}
extern "C" {
    pub fn amd_fminf(x: f32, y: f32) -> f32;
}
extern "C" {
    pub fn amd_cexp(x: fc64_t) -> fc64_t;
}
extern "C" {
    pub fn amd_cexpf(y: fc32_t) -> fc32_t;
}
extern "C" {
    pub fn amd_cpow(x: fc64_t, y: fc64_t) -> fc64_t;
}
extern "C" {
    pub fn amd_cpowf(x: fc32_t, y: fc32_t) -> fc32_t;
}
extern "C" {
    pub fn amd_clog(x: fc64_t) -> fc64_t;
}
extern "C" {
    pub fn amd_clogf(y: fc32_t) -> fc32_t;
}
extern "C" {
    pub fn amd_erf(x: f64) -> f64;
}
extern "C" {
    pub fn amd_erff(x: f32) -> f32;
}
